# **Financial GenAI Chatbot**

**Problem Statment:** Building a Financial GenAI Base Chatbot for answering Company Specific product queries and helping customer to use and buy products effectively. I build this project using Python, Langchain and LLM (open source).

In [4]:
pip install google.colab

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement google.colab (from versions: none)
ERROR: No matching distribution found for google.colab

In [1]:


import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
import os

# Check current working directory
print("Current working directory:")
print(os.getcwd())

# Example: set a local project directory (OPTIONAL)
# os.chdir("C:/Users/YourUsername/Documents/ProjectFolder")  # Windows
# os.chdir("/home/username/projectfolder")                   # Linux / Mac

# Example: load a local file
file_path = "D:\Welingkar\TRI 5\Fintech\BankFAQs.csv"   # file should be in the current directory

if os.path.exists(file_path):
    print("File found:", file_path)
else:
    print("File not found. Please check the path.")

Current working directory:
d:\Welingkar\TRI 5\Fintech
File found: D:\Welingkar\TRI 5\Fintech\BankFAQs.csv

<>:12: SyntaxWarning: invalid escape sequence '\W'
<>:12: SyntaxWarning: invalid escape sequence '\W'
C:\Users\pirat\AppData\Local\Temp\ipykernel_25536\4260917276.py:12: SyntaxWarning: invalid escape sequence '\W'
  file_path = "D:\Welingkar\TRI 5\Fintech\BankFAQs.csv"   # file should be in the current directory

# Building the GenAI Finance Chatbot

In [4]:
import pandas as pd
import numpy as np
import os
import warnings
warnings.filterwarnings('ignore')

### Loading the Data

In [6]:
bank = pd.read_csv("D:\Welingkar\TRI 5\Fintech\BankFAQs.csv")
bank.head()

,Question,Answer,Class
0,What are the documents required for opening a ...,Following documents are required to open a Cur...,accounts
1,Can I transfer my Current Account from one bra...,"Yes, Current Accounts can be transferred from ...",accounts
2,My present status is NRI. What extra documents...,NRI/PIO can open the proprietorship/partnershi...,accounts
3,What are the documents required for opening a ...,Following documents are required for opening a...,accounts
4,What documents are required to change the addr...,Following documents are required to change the...,accounts

In [7]:
bank["content"] = bank.apply(lambda row: f"Question: {row['Question']}\nAnswer: {row['Answer']}", axis=1)

This line of code creates a new column called "content" in the DataFrame bank, which is constructed by combining the "Question" and "Answer" columns in a formatted way.

    bank.apply(...): This applies a function to each row in the DataFrame. Here, it iterates through each row of the bank DataFrame.

    lambda row: f"Question: {row['Question']}\nAnswer: {row['Answer']}":
        The lambda row part defines an inline function that takes each row as an input.
        f"Question: {row['Question']}\nAnswer: {row['Answer']}" is an f-string that formats the "Question" and "Answer" from each row.
        For each row, it places "Question: " before the question text and "Answer: " before the answer text, separated by a newline \n.

    axis=1: Specifies that the function should be applied row by row (across columns).

    Assigning to bank["content"]: The formatted result is assigned to a new column named "content" in the bank DataFrame.

Significance

The new "content" column combines each question and answer pair in a single formatted string, making it easier to pass into models or search algorithms that take combined text inputs. This column is particularly useful when working with models designed for question-answering tasks, as it provides a clear structure for each FAQ entry.
Example Output

For a row where:

    Question is: "What are the bank's operating hours?"
    Answer is: "The bank operates from 9 AM to 5 PM, Monday through Friday."

The "content" column will contain:

vbnet

Question: What are the bank's operating hours?
Answer: The bank operates from 9 AM to 5 PM, Monday through Friday.

This consolidated format can be directly used in applications like a chatbot or FAQ retrieval system, streamlining the input text for more effective processing.

In [8]:
bank.head()

,Question,Answer,Class,content
0,What are the documents required for opening a ...,Following documents are required to open a Cur...,accounts,Question: What are the documents required for ...
1,Can I transfer my Current Account from one bra...,"Yes, Current Accounts can be transferred from ...",accounts,Question: Can I transfer my Current Account fr...
2,My present status is NRI. What extra documents...,NRI/PIO can open the proprietorship/partnershi...,accounts,Question: My present status is NRI. What extra...
3,What are the documents required for opening a ...,Following documents are required for opening a...,accounts,Question: What are the documents required for ...
4,What documents are required to change the addr...,Following documents are required to change the...,accounts,Question: What documents are required to chang...

In [2]:
pip install langchain

Requirement already satisfied: langchain in d:\shared\software\python\lib\site-packages (1.2.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.1 in d:\shared\software\python\lib\site-packages (from langchain) (1.2.6)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in d:\shared\software\python\lib\site-packages (from langchain) (1.0.5)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in d:\shared\software\python\lib\site-packages (from langchain) (2.12.5)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in d:\shared\software\python\lib\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in d:\shared\software\python\lib\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (0.6.0)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in c:\users\pirat\appdata\roaming\python\python313\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in d:\shared\software\python\lib\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in d:\shared\software\python\lib\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (8.5.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in d:\shared\software\python\lib\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in d:\shared\software\python\lib\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (0.12.0)
Requirement already satisfied: jsonpointer>=1.9 in d:\shared\software\python\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.1->langchain) (3.0.0)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (1.0.5)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (0.3.1)
Requirement already satisfied: xxhash>=3.5.0 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.6.0)
Requirement already satisfied: ormsgpack>=1.12.0 in d:\shared\software\python\lib\site-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain) (1.12.1)
Requirement already satisfied: httpx>=0.25.2 in d:\shared\software\python\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.10.1 in d:\shared\software\python\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in d:\shared\software\python\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in d:\shared\software\python\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in d:\shared\software\python\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (0.25.0)
Requirement already satisfied: anyio in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (4.12.0)
Requirement already satisfied: certifi in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (2025.11.12)
Requirement already satisfied: httpcore==1.* in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (1.0.9)
Requirement already satisfied: idna in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11)
Requirement already satisfied: h11>=0.16 in d:\shared\software\python\lib\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in d:\shared\software\python\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in d:\shared\software\python\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in d:\shared\software\python\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\shared\software\python\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\shared\software\python\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (2.5.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install langchain langchain-community langchain-core

Requirement already satisfied: langchain in d:\shared\software\python\lib\site-packages (1.2.0)
Collecting langchain-community
  Downloading langchain_community-0.4.1-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: langchain-core in d:\shared\software\python\lib\site-packages (1.2.6)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in d:\shared\software\python\lib\site-packages (from langchain) (1.0.5)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in d:\shared\software\python\lib\site-packages (from langchain) (2.12.5)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in d:\shared\software\python\lib\site-packages (from langchain-core) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in d:\shared\software\python\lib\site-packages (from langchain-core) (0.6.0)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in c:\users\pirat\appdata\roaming\python\python313\site-packages (from langchain-core) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in d:\shared\software\python\lib\site-packages (from langchain-core) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in d:\shared\software\python\lib\site-packages (from langchain-core) (8.5.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in d:\shared\software\python\lib\site-packages (from langchain-core) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in d:\shared\software\python\lib\site-packages (from langchain-core) (0.12.0)
Requirement already satisfied: jsonpointer>=1.9 in d:\shared\software\python\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core) (3.0.0)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (1.0.5)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (0.3.1)
Requirement already satisfied: xxhash>=3.5.0 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.6.0)
Requirement already satisfied: ormsgpack>=1.12.0 in d:\shared\software\python\lib\site-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain) (1.12.1)
Requirement already satisfied: httpx>=0.25.2 in d:\shared\software\python\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.10.1 in d:\shared\software\python\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in d:\shared\software\python\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in d:\shared\software\python\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in d:\shared\software\python\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (0.25.0)
Requirement already satisfied: anyio in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (4.12.0)
Requirement already satisfied: certifi in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (2025.11.12)
Requirement already satisfied: httpcore==1.* in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (1.0.9)
Requirement already satisfied: idna in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11)
Requirement already satisfied: h11>=0.16 in d:\shared\software\python\lib\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in d:\shared\software\python\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in d:\shared\software\python\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in d:\shared\software\python\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Collecting langchain-classic<2.0.0,>=1.0.0 (from langchain-community)
  Downloading langchain_classic-1.0.1-py3-none-any.whl.metadata (4.2 kB)
Collecting SQLAlchemy<3.0.0,>=1.4.0 (from langchain-community)
  Downloading sqlalchemy-2.0.45-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain-community)
  Downloading aiohttp-3.13.3-cp313-cp313-win_amd64.whl.metadata (8.4 kB)
Collecting dataclasses-json<0.7.0,>=0.6.7 (from langchain-community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain-community)
  Downloading pydantic_settings-2.12.0-py3-none-any.whl.metadata (3.4 kB)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community)
  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: numpy>=2.1.0 in d:\shared\software\python\lib\site-packages (from langchain-community) (2.3.4)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading frozenlist-1.8.0-cp313-cp313-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading multidict-6.7.0-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading propcache-0.4.1-cp313-cp313-win_amd64.whl.metadata (14 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading yarl-1.22.0-cp313-cp313-win_amd64.whl.metadata (77 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting langchain-text-splitters<2.0.0,>=1.1.0 (from langchain-classic<2.0.0,>=1.0.0->langchain-community)
  Downloading langchain_text_splitters-1.1.0-py3-none-any.whl.metadata (2.7 kB)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.10.1->langchain-community)
  Downloading python_dotenv-1.2.1-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\shared\software\python\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\shared\software\python\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core) (2.5.0)
Collecting greenlet>=1 (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community)
  Downloading greenlet-3.3.0-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: mypy-extensions>=0.3.0 in d:\shared\software\python\lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community) (1.1.0)
Downloading langchain_community-0.4.1-py3-none-any.whl (2.5 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   -------------------- ------------------- 1.3/2.5 MB 7.3 MB/s eta 0:00:01
   ---------------------------------------- 2.5/2.5 MB 9.0 MB/s  0:00:00
Downloading aiohttp-3.13.3-cp313-cp313-win_amd64.whl (453 kB)
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Downloading langchain_classic-1.0.1-py3-none-any.whl (1.0 MB)
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   ---------------------------------------- 1.0/1.0 MB 11.7 MB/s  0:00:00
Downloading langchain_text_splitters-1.1.0-py3-none-any.whl (34 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
Downloading multidict-6.7.0-cp313-cp313-win_amd64.whl (45 kB)
Downloading pydantic_settings-2.12.0-py3-none-any.whl (51 kB)
Downloading sqlalchemy-2.0.45-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 13.3 MB/s  0:00:00
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading yarl-1.22.0-cp313-cp313-win_amd64.whl (86 kB)
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading attrs-25.4.0-py3-none-any.whl (67 kB)
Downloading frozenlist-1.8.0-cp313-cp313-win_amd64.whl (43 kB)
Downloading greenlet-3.3.0-cp313-cp313-win_amd64.whl (301 kB)
Downloading propcache-0.4.1-cp313-cp313-win_amd64.whl (40 kB)
Downloading python_dotenv-1.2.1-py3-none-any.whl (21 kB)
Installing collected packages: typing-inspect, python-dotenv, propcache, multidict, marshmallow, httpx-sse, greenlet, frozenlist, attrs, aiohappyeyeballs, yarl, SQLAlchemy, dataclasses-json, aiosignal, pydantic-settings, aiohttp, langchain-text-splitters, langchain-classic, langchain-community

   ----------------------------------------  0/19 [typing-inspect]
   ----------------------------------------  0/19 [typing-inspect]
   -- -------------------------------------  1/19 [python-dotenv]
   -- -------------------------------------  1/19 [python-dotenv]
   ---- -----------------------------------  2/19 [propcache]
   ------ ---------------------------------  3/19 [multidict]
   ------ ---------------------------------  3/19 [multidict]
   -------- -------------------------------  4/19 [marshmallow]
   -------- -------------------------------  4/19 [marshmallow]
   ---------- -----------------------------  5/19 [httpx-sse]
   ---------- -----------------------------  5/19 [httpx-sse]
   ------------ ---------------------------  6/19 [greenlet]
   ------------ ---------------------------  6/19 [greenlet]
   ------------ ---------------------------  6/19 [greenlet]
   -------------- -------------------------  7/19 [frozenlist]
   ---------------- -----------------------  8/19 [attrs]
   ---------------- -----------------------  8/19 [attrs]
   ---------------- -----------------------  8/19 [attrs]
   ------------------ ---------------------  9/19 [aiohappyeyeballs]
   --------------------- ------------------ 10/19 [yarl]
   --------------------- ------------------ 10/19 [yarl]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ----------------------- ---------------- 11/19 [SQLAlchemy]
   ------------------------- -------------- 12/19 [dataclasses-json]
   ------------------------- -------------- 12/19 [dataclasses-json]
   --------------------------- ------------ 13/19 [aiosignal]
   ----------------------------- ---------- 14/19 [pydantic-settings]
   ----------------------------- ---------- 14/19 [pydantic-settings]
   ----------------------------- ---------- 14/19 [pydantic-settings]
   ------------------------------- -------- 15/19 [aiohttp]
   ------------------------------- -------- 15/19 [aiohttp]
   ------------------------------- -------- 15/19 [aiohttp]
   ------------------------------- -------- 15/19 [aiohttp]
   ------------------------------- -------- 15/19 [aiohttp]
   ------------------------------- -------- 15/19 [aiohttp]
   ------------------------------- -------- 15/19 [aiohttp]
   ------------------------------- -------- 15/19 [aiohttp]
   ------------------------------- -------- 15/19 [aiohttp]
   ------------------------------- -------- 15/19 [aiohttp]
   --------------------------------- ------ 16/19 [langchain-text-splitters]
   --------------------------------- ------ 16/19 [langchain-text-splitters]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]
   ----------------------------------- ---- 17/19 [langchain-classic]

  WARNING: The script dotenv.exe is installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [2]:
pip install --upgrade langchain

Requirement already satisfied: langchain in d:\shared\software\python\lib\site-packages (1.2.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.1 in d:\shared\software\python\lib\site-packages (from langchain) (1.2.6)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in d:\shared\software\python\lib\site-packages (from langchain) (1.0.5)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in d:\shared\software\python\lib\site-packages (from langchain) (2.12.5)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in d:\shared\software\python\lib\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in d:\shared\software\python\lib\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (0.6.0)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in c:\users\pirat\appdata\roaming\python\python313\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in d:\shared\software\python\lib\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in d:\shared\software\python\lib\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (8.5.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in d:\shared\software\python\lib\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in d:\shared\software\python\lib\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (0.12.0)
Requirement already satisfied: jsonpointer>=1.9 in d:\shared\software\python\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.1->langchain) (3.0.0)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (1.0.5)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (0.3.1)
Requirement already satisfied: xxhash>=3.5.0 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.6.0)
Requirement already satisfied: ormsgpack>=1.12.0 in d:\shared\software\python\lib\site-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain) (1.12.1)
Requirement already satisfied: httpx>=0.25.2 in d:\shared\software\python\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.10.1 in d:\shared\software\python\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in d:\shared\software\python\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in d:\shared\software\python\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in d:\shared\software\python\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (0.25.0)
Requirement already satisfied: anyio in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (4.12.0)
Requirement already satisfied: certifi in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (2025.11.12)
Requirement already satisfied: httpcore==1.* in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (1.0.9)
Requirement already satisfied: idna in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11)
Requirement already satisfied: h11>=0.16 in d:\shared\software\python\lib\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in d:\shared\software\python\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in d:\shared\software\python\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in d:\shared\software\python\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\shared\software\python\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\shared\software\python\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (2.5.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd
from langchain_core.documents import Document

# Load CSV
bank = pd.read_csv("D:\Welingkar\TRI 5\Fintech\BankFAQs.csv")

# Inspect actual column names
print("Available columns:", list(bank.columns))

# --- MAP your real columns here ---
CONTENT_COL = "Question"   # change if needed
CLASS_COL = "Answer"       # change if needed

# Validate mapping
if CONTENT_COL not in bank.columns or CLASS_COL not in bank.columns:
    raise ValueError("Update CONTENT_COL and CLASS_COL to match your CSV columns")

# Create LangChain documents
documents = [
    Document(
        page_content=str(row[CONTENT_COL]),
        metadata={"class": row[CLASS_COL]}
    )
    for _, row in bank.iterrows()
]

print(f"Created {len(documents)} documents successfully")

Available columns: ['Question', 'Answer', 'Class']
Created 1773 documents successfully

<>:5: SyntaxWarning: invalid escape sequence '\W'
<>:5: SyntaxWarning: invalid escape sequence '\W'
C:\Users\pirat\AppData\Local\Temp\ipykernel_25524\2070544326.py:5: SyntaxWarning: invalid escape sequence '\W'
  bank = pd.read_csv("D:\Welingkar\TRI 5\Fintech\BankFAQs.csv")

This code creates a list of Document objects, each containing the question-answer pairs from the "content" column in bank, along with a classification label (or metadata) from the "Class" column. Let's go through each part in detail:
Explanation

    Importing Document:
        from langchain.docstore.document import Document: Imports the Document class from LangChain, which is used to structure data for natural language processing applications.

    Creating an Empty List:
        documents = []: Initializes an empty list called documents to store the formatted Document objects.

    Iterating Over Each Row in bank:
        for _, row in bank.iterrows(): Loops through each row in the DataFrame bank using .iterrows(), which provides each row’s index (_) and data (row) as a series.

    Creating Document Instances:
        Document(page_content=row["content"], metadata={"class": row["Class"]}): For each row, a Document object is created with:
            page_content=row["content"]: The text content (question and answer) from the "content" column.
            metadata={"class": row["Class"]}: Metadata attached to the Document, specifically the category or classification label from the "Class" column in the DataFrame.
        documents.append(...): Adds each Document instance to the documents list.

Purpose

The purpose of this code is to format each row in bank as a structured Document object. The page_content holds the combined question-answer text, and the metadata helps classify each entry, making it easier to retrieve and categorize responses when using LangChain for search or retrieval tasks.
Example

Suppose one row in bank has:

    content: "Question: What are the bank's operating hours?\nAnswer: The bank operates from 9 AM to 5 PM, Monday through Friday."
    Class: "General Information"
    This structured format enables efficient storage and retrieval in a document-based system like LangChain, allowing for easy filtering and access to documents based on both content and metadata.

In [8]:
documents[1]

Document(metadata={'class': 'Yes, Current Accounts can be transferred from one branch to another. However, there are certain restrictions. Please visit your nearest branch for details.'}, page_content='Can I transfer my Current Account from one branch to another')

In [9]:
pip install langchain_community

Defaulting to user installation because normal site-packages is not writeable
Collecting langchain_community
  Downloading langchain_community-0.3.31-py3-none-any.whl (2.5 MB)
Collecting httpx-sse<1.0.0,>=0.4.0
  Downloading httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Collecting langchain<2.0.0,>=0.3.27
  Downloading langchain-0.3.27-py3-none-any.whl (1.0 MB)
Collecting PyYAML<7.0.0,>=5.3.0
  Downloading pyyaml-6.0.3-cp39-cp39-win_amd64.whl (158 kB)
Collecting langchain-core<2.0.0,>=0.3.78
  Downloading langchain_core-0.3.81-py3-none-any.whl (457 kB)
Collecting requests<3.0.0,>=2.32.5
  Downloading requests-2.32.5-py3-none-any.whl (64 kB)
Collecting pydantic-settings<3.0.0,>=2.10.1
  Downloading pydantic_settings-2.11.0-py3-none-any.whl (48 kB)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in c:\users\pirat\appdata\roaming\python\python39\site-packages (from langchain_community) (1.4.31)
Collecting numpy>=1.26.2
  Downloading numpy-2.0.2-cp39-cp39-win_amd64.whl (15.9 MB)
Collecting tenacity!=8.4.0,<10.0.0,>=8.1.0
  Downloading tenacity-9.1.2-py3-none-any.whl (28 kB)
Collecting langsmith<1.0.0,>=0.1.125
  Downloading langsmith-0.4.37-py3-none-any.whl (396 kB)
Collecting dataclasses-json<0.7.0,>=0.6.7
  Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Collecting aiohttp<4.0.0,>=3.8.3
  Downloading aiohttp-3.13.3-cp39-cp39-win_amd64.whl (457 kB)
Collecting aiohappyeyeballs>=2.5.0
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.8.0-cp39-cp39-win_amd64.whl (44 kB)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.7.0-cp39-cp39-win_amd64.whl (46 kB)
Collecting yarl<2.0,>=1.17.0
  Downloading yarl-1.22.0-cp39-cp39-win_amd64.whl (87 kB)
Collecting aiosignal>=1.4.0
  Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Collecting attrs>=17.3.0
  Downloading attrs-25.4.0-py3-none-any.whl (67 kB)
Collecting propcache>=0.2.0
  Downloading propcache-0.4.1-cp39-cp39-win_amd64.whl (41 kB)
Requirement already satisfied: async-timeout<6.0,>=4.0 in c:\users\pirat\appdata\roaming\python\python39\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (4.0.2)
Requirement already satisfied: typing-extensions>=4.2 in c:\users\pirat\appdata\roaming\python\python39\site-packages (from aiosignal>=1.4.0->aiohttp<4.0.0,>=3.8.3->langchain_community) (4.5.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in c:\users\pirat\appdata\roaming\python\python39\site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain_community) (3.19.0)
Collecting typing-inspect<1,>=0.4.0
  Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Collecting pydantic<3.0.0,>=2.7.4
  Downloading pydantic-2.12.5-py3-none-any.whl (463 kB)
Collecting langchain-text-splitters<1.0.0,>=0.3.9
  Downloading langchain_text_splitters-0.3.11-py3-none-any.whl (33 kB)
Collecting typing-extensions>=4.2
  Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Collecting packaging<26.0.0,>=23.2.0
  Downloading packaging-25.0-py3-none-any.whl (66 kB)
Collecting jsonpatch<2.0.0,>=1.33.0
  Downloading jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Collecting jsonpointer>=1.9
  Downloading jsonpointer-3.0.0-py2.py3-none-any.whl (7.6 kB)
Collecting httpx<1,>=0.23.0
  Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
Collecting orjson>=3.9.14
  Downloading orjson-3.11.5-cp39-cp39-win_amd64.whl (133 kB)
Collecting zstandard>=0.23.0
  Downloading zstandard-0.25.0-cp39-cp39-win_amd64.whl (506 kB)
Collecting requests-toolbelt>=1.0.0
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Collecting anyio
  Downloading anyio-4.12.0-py3-none-any.whl (113 kB)
Requirement already satisfied: certifi in c:\users\pirat\appdata\roaming\python\python39\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (2022.6.15)
Requirement already satisfied: idna in c:\users\pirat\appdata\roaming\python\python39\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (3.3)
Collecting httpcore==1.*
  Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
Collecting h11>=0.16
  Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Collecting annotated-types>=0.6.0
  Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Collecting pydantic-core==2.41.5
  Downloading pydantic_core-2.41.5-cp39-cp39-win_amd64.whl (2.0 MB)
Collecting typing-inspection>=0.4.2
  Downloading typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Collecting python-dotenv>=0.21.0
  Downloading python_dotenv-1.2.1-py3-none-any.whl (21 kB)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\pirat\appdata\roaming\python\python39\site-packages (from requests<3.0.0,>=2.32.5->langchain_community) (1.26.9)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\pirat\appdata\roaming\python\python39\site-packages (from requests<3.0.0,>=2.32.5->langchain_community) (2.1.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\pirat\appdata\roaming\python\python39\site-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain_community) (1.1.2)
Collecting mypy-extensions>=0.3.0
  Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Collecting exceptiongroup>=1.0.2
  Downloading exceptiongroup-1.3.1-py3-none-any.whl (16 kB)
Installing collected packages: typing-extensions, h11, exceptiongroup, typing-inspection, requests, pydantic-core, httpcore, anyio, annotated-types, zstandard, requests-toolbelt, pydantic, packaging, orjson, jsonpointer, httpx, tenacity, PyYAML, langsmith, jsonpatch, propcache, mypy-extensions, multidict, langchain-core, frozenlist, yarl, typing-inspect, python-dotenv, langchain-text-splitters, attrs, aiosignal, aiohappyeyeballs, pydantic-settings, numpy, langchain, httpx-sse, dataclasses-json, aiohttp, langchain-community
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 4.5.0
    Uninstalling typing-extensions-4.5.0:
      Successfully uninstalled typing-extensions-4.5.0
  Attempting uninstall: requests
    Found existing installation: requests 2.28.1
    Uninstalling requests-2.28.1:
      Successfully uninstalled requests-2.28.1
  Attempting uninstall: packaging
    Found existing installation: packaging 21.3
    Uninstalling packaging-21.3:
      Successfully uninstalled packaging-21.3
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.0
    Uninstalling numpy-1.22.0:
      Successfully uninstalled numpy-1.22.0
Successfully installed PyYAML-6.0.3 aiohappyeyeballs-2.6.1 aiohttp-3.13.3 aiosignal-1.4.0 annotated-types-0.7.0 anyio-4.12.0 attrs-25.4.0 dataclasses-json-0.6.7 exceptiongroup-1.3.1 frozenlist-1.8.0 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 httpx-sse-0.4.3 jsonpatch-1.33 jsonpointer-3.0.0 langchain-0.3.27 langchain-community-0.3.31 langchain-core-0.3.81 langchain-text-splitters-0.3.11 langsmith-0.4.37 multidict-6.7.0 mypy-extensions-1.1.0 numpy-2.0.2 orjson-3.11.5 packaging-25.0 propcache-0.4.1 pydantic-2.12.5 pydantic-core-2.41.5 pydantic-settings-2.11.0 python-dotenv-1.2.1 requests-2.32.5 requests-toolbelt-1.0.0 tenacity-9.1.2 typing-extensions-4.15.0 typing-inspect-0.9.0 typing-inspection-0.4.2 yarl-1.22.0 zstandard-0.25.0

  WARNING: The script httpx.exe is installed in 'C:\Users\pirat\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script dotenv.exe is installed in 'C:\Users\pirat\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\pirat\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scipy 1.8.1 requires numpy<1.25.0,>=1.17.3, but you have numpy 2.0.2 which is incompatible.
WARNING: You are using pip version 21.2.4; however, version 25.3 is available.
You should consider upgrading via the 'C:\Program Files\Python39\python.exe -m pip install --upgrade pip' command.

The langchain_community library is an extension of the core LangChain library, providing community-contributed tools, integrations, and utilities for working with LangChain in diverse applications. The purpose of langchain_community is to support additional integrations that aren’t directly included in the main LangChain library, often for third-party services or specialized use cases. Here's why it's helpful:

    Access to New Integrations:
        langchain_community offers experimental and third-party integrations that may not be available in the main LangChain library, such as models, databases, and custom APIs contributed by the community.

    Specialized Tools and Features:
        It provides tools that the community has found useful for specific NLP tasks, adding specialized prompt-handling functions, custom chain types, and additional model compatibility.

    Maintaining Core Library Stability:
        By separating experimental or community-driven components into langchain_community, the core LangChain library stays streamlined, and users can add or test features from langchain_community without affecting the core functionality.

Example Use Cases

    Custom Retrieval Models: Use community-driven integrations to leverage specific retrieval models or vector databases beyond what’s natively supported in LangChain.
    Model-Specific Chains: Easily integrate with popular models or APIs that have unique prompt or input requirements.
    Prototyping and Rapid Development: Test new tools, prompts, and functionalities created by the LangChain community without impacting your core project dependencies.

In summary, langchain_community extends LangChain's flexibility and allows users to explore community-driven enhancements, especially useful for specific NLP workflows and rapidly evolving integrations.

In [10]:
pip install sentence-transformers

Collecting sentence-transformers
  Downloading sentence_transformers-5.2.0-py3-none-any.whl.metadata (16 kB)
Collecting transformers<6.0.0,>=4.41.0 (from sentence-transformers)
  Downloading transformers-4.57.3-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: tqdm in d:\shared\software\python\lib\site-packages (from sentence-transformers) (4.67.1)
Collecting torch>=1.11.0 (from sentence-transformers)
  Downloading torch-2.9.1-cp313-cp313-win_amd64.whl.metadata (30 kB)
Requirement already satisfied: scikit-learn in d:\shared\software\python\lib\site-packages (from sentence-transformers) (1.8.0)
Requirement already satisfied: scipy in d:\shared\software\python\lib\site-packages (from sentence-transformers) (1.16.3)
Collecting huggingface-hub>=0.20.0 (from sentence-transformers)
  Downloading huggingface_hub-1.2.3-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: typing_extensions>=4.5.0 in d:\shared\software\python\lib\site-packages (from sentence-transformers) (4.15.0)
Collecting filelock (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading filelock-3.20.2-py3-none-any.whl.metadata (2.1 kB)
Collecting huggingface-hub>=0.20.0 (from sentence-transformers)
  Downloading huggingface_hub-0.36.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in d:\shared\software\python\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2.3.4)
Requirement already satisfied: packaging>=20.0 in c:\users\pirat\appdata\roaming\python\python313\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in d:\shared\software\python\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in d:\shared\software\python\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: requests in d:\shared\software\python\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2.32.5)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Collecting safetensors>=0.4.3 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading safetensors-0.7.0-cp38-abi3-win_amd64.whl.metadata (4.2 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub>=0.20.0->sentence-transformers)
  Downloading fsspec-2025.12.0-py3-none-any.whl.metadata (10 kB)
Collecting sympy>=1.13.3 (from torch>=1.11.0->sentence-transformers)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch>=1.11.0->sentence-transformers)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2 (from torch>=1.11.0->sentence-transformers)
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting setuptools (from torch>=1.11.0->sentence-transformers)
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: colorama in c:\users\pirat\appdata\roaming\python\python313\site-packages (from tqdm->sentence-transformers) (0.4.6)
Collecting MarkupSafe>=2.0 (from jinja2->torch>=1.11.0->sentence-transformers)
  Downloading markupsafe-3.0.3-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\shared\software\python\lib\site-packages (from requests->transformers<6.0.0,>=4.41.0->sentence-transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\shared\software\python\lib\site-packages (from requests->transformers<6.0.0,>=4.41.0->sentence-transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\shared\software\python\lib\site-packages (from requests->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\shared\software\python\lib\site-packages (from requests->transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.12)
Requirement already satisfied: joblib>=1.3.0 in d:\shared\software\python\lib\site-packages (from scikit-learn->sentence-transformers) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in d:\shared\software\python\lib\site-packages (from scikit-learn->sentence-transformers) (3.6.0)
Downloading sentence_transformers-5.2.0-py3-none-any.whl (493 kB)
Downloading transformers-4.57.3-py3-none-any.whl (12.0 MB)
   ---------------------------------------- 0.0/12.0 MB ? eta -:--:--
   ---------- ----------------------------- 3.1/12.0 MB 16.5 MB/s eta 0:00:01
   --------------------- ------------------ 6.6/12.0 MB 17.4 MB/s eta 0:00:01
   ----------------------------------- ---- 10.7/12.0 MB 18.3 MB/s eta 0:00:01
   ---------------------------------------- 12.0/12.0 MB 17.2 MB/s  0:00:00
Downloading huggingface_hub-0.36.0-py3-none-any.whl (566 kB)
   ---------------------------------------- 0.0/566.1 kB ? eta -:--:--
   ---------------------------------------- 566.1/566.1 kB 11.2 MB/s  0:00:00
Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 2.7/2.7 MB 18.6 MB/s  0:00:00
Downloading fsspec-2025.12.0-py3-none-any.whl (201 kB)
Downloading safetensors-0.7.0-cp38-abi3-win_amd64.whl (341 kB)
Downloading torch-2.9.1-cp313-cp313-win_amd64.whl (110.9 MB)
   ---------------------------------------- 0.0/110.9 MB ? eta -:--:--
   - -------------------------------------- 3.7/110.9 MB 19.4 MB/s eta 0:00:06
   -- ------------------------------------- 8.1/110.9 MB 19.9 MB/s eta 0:00:06
   ---- ----------------------------------- 12.3/110.9 MB 20.2 MB/s eta 0:00:05
   ----- ---------------------------------- 16.5/110.9 MB 20.4 MB/s eta 0:00:05
   ------- -------------------------------- 19.7/110.9 MB 19.0 MB/s eta 0:00:05
   -------- ------------------------------- 23.3/110.9 MB 18.8 MB/s eta 0:00:05
   ---------- ----------------------------- 27.8/110.9 MB 19.2 MB/s eta 0:00:05
   ----------- ---------------------------- 32.0/110.9 MB 19.4 MB/s eta 0:00:05
   ------------ --------------------------- 35.9/110.9 MB 19.2 MB/s eta 0:00:04
   -------------- ------------------------- 40.4/110.9 MB 19.5 MB/s eta 0:00:04
   ---------------- ----------------------- 44.6/110.9 MB 19.7 MB/s eta 0:00:04
   ----------------- ---------------------- 48.5/110.9 MB 19.5 MB/s eta 0:00:04
   ------------------ --------------------- 52.4/110.9 MB 19.4 MB/s eta 0:00:04
   -------------------- ------------------- 56.9/110.9 MB 19.6 MB/s eta 0:00:03
   ---------------------- ----------------- 61.1/110.9 MB 19.6 MB/s eta 0:00:03
   ----------------------- ---------------- 65.5/110.9 MB 19.8 MB/s eta 0:00:03
   ------------------------- -------------- 70.3/110.9 MB 19.9 MB/s eta 0:00:03
   -------------------------- ------------- 74.7/110.9 MB 20.0 MB/s eta 0:00:02
   ---------------------------- ----------- 79.2/110.9 MB 20.1 MB/s eta 0:00:02
   ------------------------------ --------- 83.9/110.9 MB 20.2 MB/s eta 0:00:02
   ------------------------------- -------- 88.6/110.9 MB 20.3 MB/s eta 0:00:02
   --------------------------------- ------ 92.0/110.9 MB 20.1 MB/s eta 0:00:01
   ---------------------------------- ----- 95.7/110.9 MB 20.0 MB/s eta 0:00:01
   ------------------------------------ --- 99.9/110.9 MB 20.0 MB/s eta 0:00:01
   ------------------------------------ -- 104.3/110.9 MB 20.1 MB/s eta 0:00:01
   --------------------------------------  108.8/110.9 MB 20.1 MB/s eta 0:00:01
   --------------------------------------  110.9/110.9 MB 20.2 MB/s eta 0:00:01
   ---------------------------------------- 110.9/110.9 MB 19.4 MB/s  0:00:05
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 17.8 MB/s  0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   ------------------------ --------------- 3.9/6.3 MB 21.0 MB/s eta 0:00:01
   ---------------------------------------- 6.3/6.3 MB 18.6 MB/s  0:00:00
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ---------------------------------------- 0.0/536.2 kB ? eta -:--:--
   ---------------------------------------- 536.2/536.2 kB 9.5 MB/s  0:00:00
Downloading filelock-3.20.2-py3-none-any.whl (16 kB)
Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading markupsafe-3.0.3-cp313-cp313-win_amd64.whl (15 kB)
Using cached setuptools-80.9.0-py3-none-any.whl (1.2 MB)
Installing collected packages: mpmath, sympy, setuptools, safetensors, networkx, MarkupSafe, fsspec, filelock, jinja2, huggingface-hub, torch, tokenizers, transformers, sentence-transformers

   ----------------------------------------  0/14 [mpmath]
   ----------------------------------------  0/14 [mpmath]
   ----------------------------------------  0/14 [mpmath]
   ----------------------------------------  0/14 [mpmath]
   ----------------------------------------  0/14 [mpmath]
   ----------------------------------------  0/14 [mpmath]
   ----------------------------------------  0/14 [mpmath]
   ----------------------------------------  0/14 [mpmath]
   ----------------------------------------  0/14 [mpmath]
   ----------------------------------------  0/14 [mpmath]
   ----------------------------------------  0/14 [mpmath]
   ----------------------------------------  0/14 [mpmath]
   ----------------------------------------  0/14 [mpmath]
   ----------------------------------------  0/14 [mpmath]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]
   -- -------------------------------------  1/14 [sympy]

  WARNING: The script isympy.exe is installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts hf.exe, huggingface-cli.exe and tiny-agents.exe are installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts torchfrtrace.exe and torchrun.exe are installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts transformers-cli.exe and transformers.exe are installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

The command !pip install sentence-transformers installs the Sentence Transformers library, which is specifically designed for tasks that require meaningful sentence-level embeddings, such as semantic search, clustering, and sentence similarity.
Significance of Sentence Transformers

    Generate Sentence Embeddings:
        Sentence Transformers allow you to convert sentences and paragraphs into dense vector representations (embeddings) that capture semantic information. This helps models understand and process the meaning of sentences beyond simple keyword matching.

    Use Pretrained Models:
        The library provides pretrained models optimized for a range of tasks, such as sentence similarity and text classification. You can start using them immediately without the need for extensive training.

    Improve NLP Applications:
        The embeddings created by Sentence Transformers are particularly useful for applications that require understanding the relationship between sentences, such as question answering, semantic search, and information retrieval.

    Compatibility with LangChain:
        In workflows like LangChain, Sentence Transformers is often used as an embedding model to support document similarity and retrieval tasks, helping retrieve relevant answers based on the semantic similarity of user queries and stored content.

Brief Explanation of Sentence Transformers

The Sentence Transformers library builds on top of the Transformer architecture, such as BERT, RoBERTa, and DistilBERT, and adapts these models for generating sentence embeddings. Sentence Transformers use a Siamese (or dual) network structure during training, which allows the model to learn high-quality embeddings for sentences by minimizing the distance between semantically similar sentences and maximizing it between dissimilar ones.
Key Features of Sentence Transformers

    Efficient Embeddings:
        It generates embeddings that are compact and easy to compare, making large-scale similarity comparisons and searches more efficient.
    Supports Fine-Tuning:
        Users can fine-tune Sentence Transformers on specific tasks if needed, though the pretrained models cover a wide range of applications out of the box.
    Broad Applications:
        Applications include question answering, semantic search, clustering, paraphrase mining, and topic modeling.

Overall, the library is widely used in applications where understanding the meaning of sentences and their similarity is essential, providing a robust solution for language understanding tasks.

### Loading Data into Chroma DB

In [1]:
from langchain_community.embeddings import HuggingFaceEmbeddings
hg_embeddings = HuggingFaceEmbeddings()

C:\Users\pirat\AppData\Local\Temp\ipykernel_22960\999870367.py:2: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEmbeddings``.
  hg_embeddings = HuggingFaceEmbeddings()
C:\Users\pirat\AppData\Local\Temp\ipykernel_22960\999870367.py:2: LangChainDeprecationWarning: Default values for HuggingFaceEmbeddings.model_name were deprecated in LangChain 0.2.16 and will be removed in 0.4.0. Explicitly pass a model_name to the HuggingFaceEmbeddings constructor instead.
  hg_embeddings = HuggingFaceEmbeddings()

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

HuggingFaceEmbeddings is a feature that allows users to easily generate text embeddings (vector representations of text) using models available on Hugging Face's Model Hub. These embeddings capture semantic meaning, making them ideal for tasks like search, information retrieval, clustering, and similarity comparisons.
Key Aspects of HuggingFaceEmbeddings

    Pretrained Models:
        Hugging Face hosts a wide variety of pretrained models (e.g., BERT, RoBERTa, Sentence Transformers) that can create embeddings tailored for different languages and tasks.
        These models produce embeddings that represent the meaning of sentences or words, making it easier to find relationships between pieces of text.

    Ease of Use:
        HuggingFaceEmbeddings simplifies the process of integrating these models into your application. You can easily load a model from the Hugging Face Hub, generate embeddings, and use them in downstream tasks.

    Versatile Applications:
        With embeddings, you can perform similarity search (finding documents that are semantically close to a given query), clustering, and other NLP tasks that require an understanding of text semantics.

    Compatibility with Libraries like LangChain:
        HuggingFaceEmbeddings is commonly used in libraries like LangChain for tasks like question-answering, search engines, and chatbots, enabling you to retrieve and match relevant text based on semantic similarity.

Example Usage in NLP Applications

For example, if you’re building a semantic search engine, HuggingFaceEmbeddings can help transform your documents and user queries into embeddings. You can then compare these embeddings to find the most relevant results for a query, based on meaning rather than exact keyword matches.
Advantages

    Pretrained on Large Datasets: Offers strong performance out of the box for a wide range of NLP tasks.
    Customizability: Users can fine-tune embeddings for specific tasks.
    Broad Language Support: Includes multilingual models, making it versatile for various languages and domains.

Overall, HuggingFaceEmbeddings is an efficient and accessible way to leverage powerful NLP models for extracting meaning from text and performing sophisticated semantic tasks.

A semantic search engine is an advanced type of search system that goes beyond traditional keyword matching to understand the context, intent, and meaning of user queries and documents. Unlike keyword-based search engines, which rely on matching exact terms, semantic search uses natural language processing (NLP) and machine learning techniques to capture the meanings behind words, aiming to deliver more relevant results.
Key Features of a Semantic Search Engine

    Contextual Understanding:
        It uses embeddings (vector representations) to capture the meaning of words, sentences, or paragraphs, so it can recognize that terms like "car" and "automobile" have similar meanings.
        Semantic search engines also consider context, enabling them to understand different meanings of the same word based on its use in a query.

    Intent Recognition:
        They can infer the intent behind a query. For instance, a search for "how to improve sleep" might surface documents on sleep hygiene, habits, and techniques rather than only documents with the exact phrase.

    Phrase and Synonym Matching:
        Instead of matching exact terms, semantic search finds documents that use different words but convey the same or related meanings. For example, it understands that "salary" is related to "wage" or "pay."

    Natural Language Queries:
        Users can phrase their queries in natural language, such as "What’s the best way to learn Python?" The search engine interprets the query’s meaning rather than relying only on keyword matches.

    Enhanced Relevance:
        By understanding the relationships between words and concepts, a semantic search engine can rank results by how closely they align with the user’s intent, often providing more relevant results than traditional search engines.

How Semantic Search Works

    Embedding Creation:
        Text is transformed into embeddings—numeric representations that encode semantic meaning. Models like BERT, Sentence Transformers, and others (often hosted on platforms like Hugging Face) are commonly used for this purpose.

    Query and Document Embedding Comparison:
        When a user submits a query, it’s also converted into an embedding. The engine then compares the query embedding with the document embeddings to identify those with similar meanings.

    Ranking:
        Results are ranked based on the similarity scores between the query and document embeddings. Higher similarity scores mean the content is more relevant to the user's query.

Applications of Semantic Search

Semantic search is useful in various scenarios, including:

    Customer Support: Finding relevant FAQ or knowledge base answers that match the user's question intent.
    Recommendation Systems: Matching users with similar items based on their preferences.
    Information Retrieval: Academic or research databases often use semantic search to surface relevant papers on a topic.
    E-commerce: Helping users find products that match their needs, even if they describe them differently than the product titles or descriptions.

Benefits of Semantic Search

    Better User Experience: It returns more accurate and meaningful results, often leading to higher user satisfaction.
    Enhanced Discovery: Users discover relevant information even if they use unique phrasing, synonyms, or natural language.
    More Robust Systems: By interpreting user intent and meaning, semantic search is less dependent on specific keyword matches, making it adaptable and comprehensive.

In essence, semantic search engines bring us closer to human-like understanding in search by considering the meaning and context of words, leading to richer and more accurate information retrieval.

In [2]:
pip install chromadb

Collecting chromadb
  Downloading chromadb-1.4.0-cp39-abi3-win_amd64.whl.metadata (7.3 kB)
Collecting build>=1.0.3 (from chromadb)
  Downloading build-1.3.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: pydantic>=1.9 in d:\shared\software\python\lib\site-packages (from chromadb) (2.12.5)
Collecting pybase64>=1.4.1 (from chromadb)
  Downloading pybase64-1.4.3-cp313-cp313-win_amd64.whl.metadata (9.1 kB)
Collecting uvicorn>=0.18.3 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading uvicorn-0.40.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: numpy>=1.22.5 in d:\shared\software\python\lib\site-packages (from chromadb) (2.3.4)
Collecting posthog<6.0.0,>=2.4.0 (from chromadb)
  Downloading posthog-5.4.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: typing-extensions>=4.5.0 in d:\shared\software\python\lib\site-packages (from chromadb) (4.15.0)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.23.2-cp313-cp313-win_amd64.whl.metadata (5.3 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Downloading opentelemetry_api-1.39.1-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.39.1-py3-none-any.whl.metadata (2.5 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Downloading opentelemetry_sdk-1.39.1-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: tokenizers>=0.13.2 in d:\shared\software\python\lib\site-packages (from chromadb) (0.22.2)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading PyPika-0.48.9.tar.gz (67 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: tqdm>=4.65.0 in d:\shared\software\python\lib\site-packages (from chromadb) (4.67.1)
Collecting overrides>=7.3.1 (from chromadb)
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Collecting importlib-resources (from chromadb)
  Downloading importlib_resources-6.5.2-py3-none-any.whl.metadata (3.9 kB)
Collecting grpcio>=1.58.0 (from chromadb)
  Downloading grpcio-1.76.0-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Collecting bcrypt>=4.0.1 (from chromadb)
  Downloading bcrypt-5.0.0-cp39-abi3-win_amd64.whl.metadata (10 kB)
Collecting typer>=0.9.0 (from chromadb)
  Downloading typer-0.21.0-py3-none-any.whl.metadata (16 kB)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-34.1.0-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: tenacity>=8.2.3 in d:\shared\software\python\lib\site-packages (from chromadb) (8.5.0)
Requirement already satisfied: pyyaml>=6.0.0 in d:\shared\software\python\lib\site-packages (from chromadb) (6.0.3)
Collecting mmh3>=4.0.1 (from chromadb)
  Downloading mmh3-5.2.0-cp313-cp313-win_amd64.whl.metadata (14 kB)
Requirement already satisfied: orjson>=3.9.12 in d:\shared\software\python\lib\site-packages (from chromadb) (3.11.5)
Requirement already satisfied: httpx>=0.27.0 in d:\shared\software\python\lib\site-packages (from chromadb) (0.28.1)
Collecting rich>=10.11.0 (from chromadb)
  Downloading rich-14.2.0-py3-none-any.whl.metadata (18 kB)
Collecting jsonschema>=4.19.0 (from chromadb)
  Downloading jsonschema-4.25.1-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: requests<3.0,>=2.7 in d:\shared\software\python\lib\site-packages (from posthog<6.0.0,>=2.4.0->chromadb) (2.32.5)
Requirement already satisfied: six>=1.5 in c:\users\pirat\appdata\roaming\python\python313\site-packages (from posthog<6.0.0,>=2.4.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.2 in c:\users\pirat\appdata\roaming\python\python313\site-packages (from posthog<6.0.0,>=2.4.0->chromadb) (2.9.0.post0)
Collecting backoff>=1.10.0 (from posthog<6.0.0,>=2.4.0->chromadb)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Collecting distro>=1.5.0 (from posthog<6.0.0,>=2.4.0->chromadb)
  Downloading distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\shared\software\python\lib\site-packages (from requests<3.0,>=2.7->posthog<6.0.0,>=2.4.0->chromadb) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\shared\software\python\lib\site-packages (from requests<3.0,>=2.7->posthog<6.0.0,>=2.4.0->chromadb) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\shared\software\python\lib\site-packages (from requests<3.0,>=2.7->posthog<6.0.0,>=2.4.0->chromadb) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\shared\software\python\lib\site-packages (from requests<3.0,>=2.7->posthog<6.0.0,>=2.4.0->chromadb) (2025.11.12)
Requirement already satisfied: packaging>=19.1 in c:\users\pirat\appdata\roaming\python\python313\site-packages (from build>=1.0.3->chromadb) (25.0)
Collecting pyproject_hooks (from build>=1.0.3->chromadb)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: colorama in c:\users\pirat\appdata\roaming\python\python313\site-packages (from build>=1.0.3->chromadb) (0.4.6)
Requirement already satisfied: anyio in d:\shared\software\python\lib\site-packages (from httpx>=0.27.0->chromadb) (4.12.0)
Requirement already satisfied: httpcore==1.* in d:\shared\software\python\lib\site-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: h11>=0.16 in d:\shared\software\python\lib\site-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in d:\shared\software\python\lib\site-packages (from jsonschema>=4.19.0->chromadb) (25.4.0)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=4.19.0->chromadb)
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=4.19.0->chromadb)
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.7.1 (from jsonschema>=4.19.0->chromadb)
  Downloading rpds_py-0.30.0-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Collecting google-auth>=1.0.1 (from kubernetes>=28.1.0->chromadb)
  Downloading google_auth-2.46.0-py3-none-any.whl.metadata (6.8 kB)
Collecting websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 (from kubernetes>=28.1.0->chromadb)
  Downloading websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting requests-oauthlib (from kubernetes>=28.1.0->chromadb)
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3.0,>=2.7->posthog<6.0.0,>=2.4.0->chromadb)
  Downloading urllib3-2.3.0-py3-none-any.whl.metadata (6.5 kB)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb)
  Downloading durationpy-0.10-py3-none-any.whl.metadata (340 bytes)
Collecting cachetools<7.0,>=2.0.0 (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb)
  Downloading cachetools-6.2.4-py3-none-any.whl.metadata (5.6 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb)
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting rsa<5,>=3.1.4 (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb)
  Downloading rsa-4.9.1-py3-none-any.whl.metadata (5.6 kB)
Collecting pyasn1>=0.1.3 (from rsa<5,>=3.1.4->google-auth>=1.0.1->kubernetes>=28.1.0->chromadb)
  Downloading pyasn1-0.6.1-py3-none-any.whl.metadata (8.4 kB)
Collecting coloredlogs (from onnxruntime>=1.14.1->chromadb)
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Collecting flatbuffers (from onnxruntime>=1.14.1->chromadb)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Requirement already satisfied: protobuf in d:\shared\software\python\lib\site-packages (from onnxruntime>=1.14.1->chromadb) (6.33.0)
Requirement already satisfied: sympy in d:\shared\software\python\lib\site-packages (from onnxruntime>=1.14.1->chromadb) (1.14.0)
Collecting importlib-metadata<8.8.0,>=6.0 (from opentelemetry-api>=1.2.0->chromadb)
  Downloading importlib_metadata-8.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting zipp>=3.20 (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb)
  Downloading zipp-3.23.0-py3-none-any.whl.metadata (3.6 kB)
Collecting googleapis-common-protos~=1.57 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading googleapis_common_protos-1.72.0-py3-none-any.whl.metadata (9.4 kB)
Collecting opentelemetry-exporter-otlp-proto-common==1.39.1 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_exporter_otlp_proto_common-1.39.1-py3-none-any.whl.metadata (1.8 kB)
Collecting opentelemetry-proto==1.39.1 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_proto-1.39.1-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-semantic-conventions==0.60b1 (from opentelemetry-sdk>=1.2.0->chromadb)
  Downloading opentelemetry_semantic_conventions-0.60b1-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: annotated-types>=0.6.0 in d:\shared\software\python\lib\site-packages (from pydantic>=1.9->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in d:\shared\software\python\lib\site-packages (from pydantic>=1.9->chromadb) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in d:\shared\software\python\lib\site-packages (from pydantic>=1.9->chromadb) (0.4.2)
Collecting markdown-it-py>=2.2.0 (from rich>=10.11.0->chromadb)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\pirat\appdata\roaming\python\python313\site-packages (from rich>=10.11.0->chromadb) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in d:\shared\software\python\lib\site-packages (from tokenizers>=0.13.2->chromadb) (0.36.0)
Requirement already satisfied: filelock in d:\shared\software\python\lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.20.2)
Requirement already satisfied: fsspec>=2023.5.0 in d:\shared\software\python\lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2025.12.0)
Requirement already satisfied: click>=8.0.0 in d:\shared\software\python\lib\site-packages (from typer>=0.9.0->chromadb) (8.3.1)
Collecting shellingham>=1.3.0 (from typer>=0.9.0->chromadb)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting httptools>=0.6.3 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading httptools-0.7.1-cp313-cp313-win_amd64.whl.metadata (3.6 kB)
Requirement already satisfied: python-dotenv>=0.13 in d:\shared\software\python\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.2.1)
Collecting watchfiles>=0.13 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading watchfiles-1.1.1-cp313-cp313-win_amd64.whl.metadata (5.0 kB)
Requirement already satisfied: websockets>=10.4 in d:\shared\software\python\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime>=1.14.1->chromadb)
  Downloading humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Collecting pyreadline3 (from humanfriendly>=9.1->coloredlogs->onnxruntime>=1.14.1->chromadb)
  Downloading pyreadline3-3.5.4-py3-none-any.whl.metadata (4.7 kB)
Collecting oauthlib>=3.0.0 (from requests-oauthlib->kubernetes>=28.1.0->chromadb)
  Downloading oauthlib-3.3.1-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\shared\software\python\lib\site-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)
Downloading chromadb-1.4.0-cp39-abi3-win_amd64.whl (21.9 MB)
   ---------------------------------------- 0.0/21.9 MB ? eta -:--:--
   - -------------------------------------- 1.0/21.9 MB 6.9 MB/s eta 0:00:04
   ----- ---------------------------------- 3.1/21.9 MB 8.6 MB/s eta 0:00:03
   ----------- ---------------------------- 6.3/21.9 MB 10.7 MB/s eta 0:00:02
   ------------------- -------------------- 10.7/21.9 MB 13.3 MB/s eta 0:00:01
   -------------------------- ------------- 14.7/21.9 MB 14.5 MB/s eta 0:00:01
   -------------------------------- ------- 18.1/21.9 MB 14.9 MB/s eta 0:00:01
   -------------------------------------- - 21.2/21.9 MB 14.9 MB/s eta 0:00:01
   ---------------------------------------- 21.9/21.9 MB 14.0 MB/s  0:00:01
Downloading posthog-5.4.0-py3-none-any.whl (105 kB)
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading bcrypt-5.0.0-cp39-abi3-win_amd64.whl (150 kB)
Downloading build-1.3.0-py3-none-any.whl (23 kB)
Downloading distro-1.9.0-py3-none-any.whl (20 kB)
Downloading grpcio-1.76.0-cp313-cp313-win_amd64.whl (4.7 MB)
   ---------------------------------------- 0.0/4.7 MB ? eta -:--:--
   -------------------------- ------------- 3.1/4.7 MB 15.8 MB/s eta 0:00:01
   ---------------------------------------- 4.7/4.7 MB 14.1 MB/s  0:00:00
Downloading jsonschema-4.25.1-py3-none-any.whl (90 kB)
Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Downloading kubernetes-34.1.0-py2.py3-none-any.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 2.0/2.0 MB 15.0 MB/s  0:00:00
Downloading urllib3-2.3.0-py3-none-any.whl (128 kB)
Downloading durationpy-0.10-py3-none-any.whl (3.9 kB)
Downloading google_auth-2.46.0-py3-none-any.whl (233 kB)
Downloading cachetools-6.2.4-py3-none-any.whl (11 kB)
Downloading rsa-4.9.1-py3-none-any.whl (34 kB)
Downloading mmh3-5.2.0-cp313-cp313-win_amd64.whl (41 kB)
Downloading onnxruntime-1.23.2-cp313-cp313-win_amd64.whl (13.5 MB)
   ---------------------------------------- 0.0/13.5 MB ? eta -:--:--
   ----------- ---------------------------- 3.9/13.5 MB 18.4 MB/s eta 0:00:01
   -------------------- ------------------- 6.8/13.5 MB 16.3 MB/s eta 0:00:01
   ---------------------------- ----------- 9.7/13.5 MB 15.4 MB/s eta 0:00:01
   -------------------------------------- - 12.8/13.5 MB 15.6 MB/s eta 0:00:01
   ---------------------------------------- 13.5/13.5 MB 15.0 MB/s  0:00:00
Downloading opentelemetry_api-1.39.1-py3-none-any.whl (66 kB)
Downloading importlib_metadata-8.7.1-py3-none-any.whl (27 kB)
Downloading opentelemetry_exporter_otlp_proto_grpc-1.39.1-py3-none-any.whl (19 kB)
Downloading opentelemetry_exporter_otlp_proto_common-1.39.1-py3-none-any.whl (18 kB)
Downloading opentelemetry_proto-1.39.1-py3-none-any.whl (72 kB)
Downloading googleapis_common_protos-1.72.0-py3-none-any.whl (297 kB)
Downloading opentelemetry_sdk-1.39.1-py3-none-any.whl (132 kB)
Downloading opentelemetry_semantic_conventions-0.60b1-py3-none-any.whl (219 kB)
Downloading overrides-7.7.0-py3-none-any.whl (17 kB)
Downloading pyasn1-0.6.1-py3-none-any.whl (83 kB)
Downloading pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Downloading pybase64-1.4.3-cp313-cp313-win_amd64.whl (35 kB)
Downloading referencing-0.37.0-py3-none-any.whl (26 kB)
Downloading rich-14.2.0-py3-none-any.whl (243 kB)
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading rpds_py-0.30.0-cp313-cp313-win_amd64.whl (240 kB)
Downloading typer-0.21.0-py3-none-any.whl (47 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Downloading uvicorn-0.40.0-py3-none-any.whl (68 kB)
Downloading httptools-0.7.1-cp313-cp313-win_amd64.whl (85 kB)
Downloading watchfiles-1.1.1-cp313-cp313-win_amd64.whl (288 kB)
Downloading websocket_client-1.9.0-py3-none-any.whl (82 kB)
Downloading zipp-3.23.0-py3-none-any.whl (10 kB)
Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Downloading flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Downloading importlib_resources-6.5.2-py3-none-any.whl (37 kB)
Downloading pyproject_hooks-1.2.0-py3-none-any.whl (10 kB)
Downloading pyreadline3-3.5.4-py3-none-any.whl (83 kB)
Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Downloading oauthlib-3.3.1-py3-none-any.whl (160 kB)
Building wheels for collected packages: pypika
  Building wheel for pypika (pyproject.toml): started
  Building wheel for pypika (pyproject.toml): finished with status 'done'
  Created wheel for pypika: filename=pypika-0.48.9-py2.py3-none-any.whl size=53916 sha256=28f3bf5b39ce70f79984c3f05bc2f3dbc1cd1ebc04f58d56248820789c3ac085
  Stored in directory: c:\users\pirat\appdata\local\pip\cache\wheels\b4\f8\a5\28e9c1524d320f4b8eefdce0e487b5c2e128dbf2ed1bb4a60b
Successfully built pypika
Installing collected packages: pypika, flatbuffers, durationpy, zipp, websocket-client, urllib3, shellingham, rpds-py, pyreadline3, pyproject_hooks, pybase64, pyasn1, overrides, opentelemetry-proto, oauthlib, mmh3, mdurl, importlib-resources, httptools, grpcio, googleapis-common-protos, distro, cachetools, bcrypt, backoff, watchfiles, uvicorn, rsa, referencing, pyasn1-modules, opentelemetry-exporter-otlp-proto-common, markdown-it-py, importlib-metadata, humanfriendly, build, rich, requests-oauthlib, posthog, opentelemetry-api, jsonschema-specifications, google-auth, coloredlogs, typer, opentelemetry-semantic-conventions, onnxruntime, kubernetes, jsonschema, opentelemetry-sdk, opentelemetry-exporter-otlp-proto-grpc, chromadb

   ----------------------------------------  0/50 [pypika]
   ----------------------------------------  0/50 [pypika]
   ----------------------------------------  0/50 [pypika]
   ----------------------------------------  0/50 [pypika]
    ---------------------------------------  1/50 [flatbuffers]
    ---------------------------------------  1/50 [flatbuffers]
   -- -------------------------------------  3/50 [zipp]
   -- -------------------------------------  3/50 [zipp]
   --- ------------------------------------  4/50 [websocket-client]
   --- ------------------------------------  4/50 [websocket-client]
   --- ------------------------------------  4/50 [websocket-client]
   --- ------------------------------------  4/50 [websocket-client]
   --- ------------------------------------  4/50 [websocket-client]
  Attempting uninstall: urllib3
   --- ------------------------------------  4/50 [websocket-client]
    Found existing installation: urllib3 2.5.0
   --- ------------------------------------  4/50 [websocket-client]
   ---- -----------------------------------  5/50 [urllib3]
    Uninstalling urllib3-2.5.0:
   ---- -----------------------------------  5/50 [urllib3]
      Successfully uninstalled urllib3-2.5.0
   ---- -----------------------------------  5/50 [urllib3]
   ---- -----------------------------------  5/50 [urllib3]
   ---- -----------------------------------  5/50 [urllib3]
   ---- -----------------------------------  5/50 [urllib3]
   ---- -----------------------------------  5/50 [urllib3]
   ---- -----------------------------------  5/50 [urllib3]
   ---- -----------------------------------  5/50 [urllib3]
   ---- -----------------------------------  6/50 [shellingham]
   ----- ----------------------------------  7/50 [rpds-py]
   ------ ---------------------------------  8/50 [pyreadline3]
   ------ ---------------------------------  8/50 [pyreadline3]
   ------ ---------------------------------  8/50 [pyreadline3]
   ------ ---------------------------------  8/50 [pyreadline3]
   ------ ---------------------------------  8/50 [pyreadline3]
   ------ ---------------------------------  8/50 [pyreadline3]
   ------- --------------------------------  9/50 [pyproject_hooks]

  WARNING: The script wsdump.exe is installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pybase64.exe is installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script distro.exe is installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script watchfiles.exe is installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script uvicorn.exe is installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts pyrsa-decrypt.exe, pyrsa-encrypt.exe, pyrsa-keygen.exe, pyrsa-priv2pub.exe, pyrsa-sign.exe and pyrsa-verify.exe are installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script markdown-it.exe is installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script humanfriendly.exe is installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pyproject-build.exe is installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script coloredlogs.exe is installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script typer.exe is installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script onnxruntime_test.exe is installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script jsonschema.exe is installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script chroma.exe is installed in 'd:\Shared\Software\Python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

The command !pip install chromadb installs Chroma, an open-source vector database designed for high-performance storage, retrieval, and querying of vector embeddings. Chroma is optimized for handling dense vector representations, often used in semantic search, recommendation engines, NLP applications, and other machine learning tasks.
Key Features and Significance of ChromaDB

    Efficient Embedding Storage and Retrieval:
        Chroma is designed to store vector embeddings (numeric representations of text, images, or other data) and retrieve them quickly. This is particularly important for semantic search applications where embeddings need to be compared based on similarity scores.

    Scalability:
        ChromaDB handles large volumes of embeddings, allowing for effective scaling in production-grade applications, making it suitable for projects that involve massive datasets or real-time processing.

    Integration with ML Pipelines:
        Chroma integrates easily with machine learning workflows, providing support for various vector embedding formats, and it’s often used with NLP models and frameworks like Hugging Face or Sentence Transformers.

    Application in Semantic Search:
        In semantic search, embeddings of queries and documents are compared to find the closest matches. ChromaDB enables fast and efficient nearest-neighbor search, which is crucial for ranking and retrieving relevant documents or items based on similarity to a query.

Why ChromaDB is Significant

    High-Speed Vector Processing: Optimized for similarity search, Chroma is ideal for real-time applications that require fast response times.
    Flexible and Open-Source: As an open-source solution, ChromaDB is accessible, and users can customize it to fit their needs without licensing fees.
    Supports Advanced ML Applications: Whether it's for building recommendation systems, semantic search engines, or clustering tasks, Chroma’s ability to handle embeddings makes it invaluable in NLP and ML projects.

In summary, ChromaDB is a powerful choice for applications that require fast, scalable, and accurate retrieval of vector embeddings, making it a foundational tool for developing AI-powered search and recommendation systems.

In [7]:
import pandas as pd
from langchain_core.documents import Document
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

# ---------- 1. Load data ----------
bank = pd.read_csv("D:\Welingkar\TRI 5\Fintech\BankFAQs.csv")

# Update column names to match your CSV
CONTENT_COL = "Question"
CLASS_COL = "Answer"

# ---------- 2. Create documents ----------
documents = [
    Document(
        page_content=str(row[CONTENT_COL]),
        metadata={"class": row[CLASS_COL]}
    )
    for _, row in bank.iterrows()
]

# ---------- 3. Create embeddings ----------
hg_embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

# ---------- 4. Create Chroma vector store ----------
persist_directory = "/kaggle/working/"

langchain_chroma = Chroma.from_documents(
    documents=documents,
    collection_name="chatbot_finance",
    embedding=hg_embeddings,
    persist_directory=persist_directory
)

print("Chroma vector store created successfully")

<>:7: SyntaxWarning: invalid escape sequence '\W'
<>:7: SyntaxWarning: invalid escape sequence '\W'
C:\Users\pirat\AppData\Local\Temp\ipykernel_22960\262886008.py:7: SyntaxWarning: invalid escape sequence '\W'
  bank = pd.read_csv("D:\Welingkar\TRI 5\Fintech\BankFAQs.csv")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Chroma vector store created successfully

In [8]:
pip install bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.49.0-py3-none-win_amd64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in d:\shared\software\python\lib\site-packages (from bitsandbytes) (2.9.1)
Requirement already satisfied: numpy>=1.17 in d:\shared\software\python\lib\site-packages (from bitsandbytes) (2.3.4)
Requirement already satisfied: packaging>=20.9 in c:\users\pirat\appdata\roaming\python\python313\site-packages (from bitsandbytes) (25.0)
Requirement already satisfied: filelock in d:\shared\software\python\lib\site-packages (from torch<3,>=2.3->bitsandbytes) (3.20.2)
Requirement already satisfied: typing-extensions>=4.10.0 in d:\shared\software\python\lib\site-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in d:\shared\software\python\lib\site-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in d:\shared\software\python\lib\site-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in d:\shared\software\python\lib\site-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in d:\shared\software\python\lib\site-packages (from torch<3,>=2.3->bitsandbytes) (2025.12.0)
Requirement already satisfied: setuptools in d:\shared\software\python\lib\site-packages (from torch<3,>=2.3->bitsandbytes) (80.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\shared\software\python\lib\site-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\shared\software\python\lib\site-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Downloading bitsandbytes-0.49.0-py3-none-win_amd64.whl (54.7 MB)
   ---------------------------------------- 0.0/54.7 MB ? eta -:--:--
   ---------------------------------------- 0.5/54.7 MB 12.2 MB/s eta 0:00:05
   -- ------------------------------------- 2.9/54.7 MB 10.8 MB/s eta 0:00:05
   -- ------------------------------------- 3.9/54.7 MB 8.6 MB/s eta 0:00:06
   --- ------------------------------------ 4.7/54.7 MB 6.5 MB/s eta 0:00:08
   ---- ----------------------------------- 5.5/54.7 MB 5.6 MB/s eta 0:00:09
   ----- ---------------------------------- 7.9/54.7 MB 6.3 MB/s eta 0:00:08
   ------- -------------------------------- 9.7/54.7 MB 6.7 MB/s eta 0:00:07
   -------- ------------------------------- 12.1/54.7 MB 7.2 MB/s eta 0:00:06
   ---------- ----------------------------- 14.7/54.7 MB 7.8 MB/s eta 0:00:06
   ------------ --------------------------- 16.8/54.7 MB 8.0 MB/s eta 0:00:05
   -------------- ------------------------- 19.4/54.7 MB 8.4 MB/s eta 0:00:05
   --------------- ------------------------ 21.5/54.7 MB 8.6 MB/s eta 0:00:04
   ------------------ --------------------- 24.6/54.7 MB 9.0 MB/s eta 0:00:04
   -------------------- ------------------- 27.8/54.7 MB 9.5 MB/s eta 0:00:03
   ---------------------- ----------------- 30.9/54.7 MB 9.8 MB/s eta 0:00:03
   ------------------------ --------------- 33.6/54.7 MB 10.0 MB/s eta 0:00:03
   -------------------------- ------------- 36.4/54.7 MB 10.2 MB/s eta 0:00:02
   ---------------------------- ----------- 39.3/54.7 MB 10.4 MB/s eta 0:00:02
   ------------------------------- -------- 42.5/54.7 MB 10.6 MB/s eta 0:00:02
   --------------------------------- ------ 45.4/54.7 MB 10.7 MB/s eta 0:00:01
   ----------------------------------- ---- 48.0/54.7 MB 10.8 MB/s eta 0:00:01
   ------------------------------------- -- 50.9/54.7 MB 11.0 MB/s eta 0:00:01
   ---------------------------------------  53.7/54.7 MB 11.1 MB/s eta 0:00:01
   ---------------------------------------- 54.7/54.7 MB 10.9 MB/s  0:00:05
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.49.0
Note: you may need to restart the kernel to use updated packages.

### Loading the Zypher LLM

In [13]:
pip install -U langchain

Requirement already satisfied: langchain in d:\shared\software\python\lib\site-packages (1.2.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.1 in d:\shared\software\python\lib\site-packages (from langchain) (1.2.6)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in d:\shared\software\python\lib\site-packages (from langchain) (1.0.5)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in d:\shared\software\python\lib\site-packages (from langchain) (2.12.5)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in d:\shared\software\python\lib\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in d:\shared\software\python\lib\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (0.6.0)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in c:\users\pirat\appdata\roaming\python\python313\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in d:\shared\software\python\lib\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in d:\shared\software\python\lib\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (8.5.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in d:\shared\software\python\lib\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in d:\shared\software\python\lib\site-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (0.12.0)
Requirement already satisfied: jsonpointer>=1.9 in d:\shared\software\python\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.1->langchain) (3.0.0)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (1.0.5)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (0.3.1)
Requirement already satisfied: xxhash>=3.5.0 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.6.0)
Requirement already satisfied: ormsgpack>=1.12.0 in d:\shared\software\python\lib\site-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain) (1.12.1)
Requirement already satisfied: httpx>=0.25.2 in d:\shared\software\python\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.10.1 in d:\shared\software\python\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in d:\shared\software\python\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in d:\shared\software\python\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in d:\shared\software\python\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (0.25.0)
Requirement already satisfied: anyio in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (4.12.0)
Requirement already satisfied: certifi in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (2025.11.12)
Requirement already satisfied: httpcore==1.* in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (1.0.9)
Requirement already satisfied: idna in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11)
Requirement already satisfied: h11>=0.16 in d:\shared\software\python\lib\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in d:\shared\software\python\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in d:\shared\software\python\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in d:\shared\software\python\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\shared\software\python\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\shared\software\python\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (2.3.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import sys

!{sys.executable} -m pip install -U \
    langchain \
    langchain-core \
    langchain-community \
    transformers \
    accelerate \
    bitsandbytes \
    chromadb

# 2️⃣ HARD RESTART REQUIRED AFTER THIS CELL
print("Installation complete. Restart the kernel now.")

Requirement already satisfied: langchain in d:\shared\software\python\lib\site-packages (1.2.0)
Requirement already satisfied: langchain-core in d:\shared\software\python\lib\site-packages (1.2.6)
Requirement already satisfied: langchain-community in d:\shared\software\python\lib\site-packages (0.4.1)
Requirement already satisfied: transformers in d:\shared\software\python\lib\site-packages (4.57.3)
Requirement already satisfied: accelerate in d:\shared\software\python\lib\site-packages (1.12.0)
Requirement already satisfied: bitsandbytes in d:\shared\software\python\lib\site-packages (0.49.0)
Requirement already satisfied: chromadb in d:\shared\software\python\lib\site-packages (1.4.0)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in d:\shared\software\python\lib\site-packages (from langchain) (1.0.5)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in d:\shared\software\python\lib\site-packages (from langchain) (2.12.5)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in d:\shared\software\python\lib\site-packages (from langchain-core) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in d:\shared\software\python\lib\site-packages (from langchain-core) (0.6.0)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in c:\users\pirat\appdata\roaming\python\python313\site-packages (from langchain-core) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in d:\shared\software\python\lib\site-packages (from langchain-core) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in d:\shared\software\python\lib\site-packages (from langchain-core) (8.5.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in d:\shared\software\python\lib\site-packages (from langchain-core) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in d:\shared\software\python\lib\site-packages (from langchain-core) (0.12.0)
Requirement already satisfied: jsonpointer>=1.9 in d:\shared\software\python\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core) (3.0.0)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (1.0.5)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (0.3.1)
Requirement already satisfied: xxhash>=3.5.0 in d:\shared\software\python\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.6.0)
Requirement already satisfied: ormsgpack>=1.12.0 in d:\shared\software\python\lib\site-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain) (1.12.1)
Requirement already satisfied: httpx>=0.25.2 in d:\shared\software\python\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.10.1 in d:\shared\software\python\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in d:\shared\software\python\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in d:\shared\software\python\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in d:\shared\software\python\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (0.25.0)
Requirement already satisfied: anyio in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (4.12.0)
Requirement already satisfied: certifi in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (2025.11.12)
Requirement already satisfied: httpcore==1.* in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (1.0.9)
Requirement already satisfied: idna in d:\shared\software\python\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11)
Requirement already satisfied: h11>=0.16 in d:\shared\software\python\lib\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in d:\shared\software\python\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in d:\shared\software\python\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in d:\shared\software\python\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in d:\shared\software\python\lib\site-packages (from langchain-community) (1.0.1)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in d:\shared\software\python\lib\site-packages (from langchain-community) (2.0.45)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in d:\shared\software\python\lib\site-packages (from langchain-community) (3.13.3)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in d:\shared\software\python\lib\site-packages (from langchain-community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in d:\shared\software\python\lib\site-packages (from langchain-community) (2.12.0)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in d:\shared\software\python\lib\site-packages (from langchain-community) (0.4.3)
Requirement already satisfied: numpy>=2.1.0 in d:\shared\software\python\lib\site-packages (from langchain-community) (2.3.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in d:\shared\software\python\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in d:\shared\software\python\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in d:\shared\software\python\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in d:\shared\software\python\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\shared\software\python\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in d:\shared\software\python\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in d:\shared\software\python\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.22.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in d:\shared\software\python\lib\site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in d:\shared\software\python\lib\site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (0.9.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.0 in d:\shared\software\python\lib\site-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community) (1.1.0)
Requirement already satisfied: python-dotenv>=0.21.0 in d:\shared\software\python\lib\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.1)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\shared\software\python\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\shared\software\python\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core) (2.3.0)
Requirement already satisfied: greenlet>=1 in d:\shared\software\python\lib\site-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community) (3.3.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in d:\shared\software\python\lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community) (1.1.0)
Requirement already satisfied: filelock in d:\shared\software\python\lib\site-packages (from transformers) (3.20.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in d:\shared\software\python\lib\site-packages (from transformers) (0.36.0)
Requirement already satisfied: regex!=2019.12.17 in d:\shared\software\python\lib\site-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in d:\shared\software\python\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in d:\shared\software\python\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in d:\shared\software\python\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in d:\shared\software\python\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.12.0)
Requirement already satisfied: psutil in c:\users\pirat\appdata\roaming\python\python313\site-packages (from accelerate) (7.1.3)
Requirement already satisfied: torch>=2.0.0 in d:\shared\software\python\lib\site-packages (from accelerate) (2.9.1)
Requirement already satisfied: sympy>=1.13.3 in d:\shared\software\python\lib\site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in d:\shared\software\python\lib\site-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in d:\shared\software\python\lib\site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: setuptools in d:\shared\software\python\lib\site-packages (from torch>=2.0.0->accelerate) (80.9.0)
Requirement already satisfied: build>=1.0.3 in d:\shared\software\python\lib\site-packages (from chromadb) (1.3.0)
Requirement already satisfied: pybase64>=1.4.1 in d:\shared\software\python\lib\site-packages (from chromadb) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in d:\shared\software\python\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.40.0)
Requirement already satisfied: posthog<6.0.0,>=2.4.0 in d:\shared\software\python\lib\site-packages (from chromadb) (5.4.0)
Requirement already satisfied: onnxruntime>=1.14.1 in d:\shared\software\python\lib\site-packages (from chromadb) (1.23.2)
Requirement already satisfied: opentelemetry-api>=1.2.0 in d:\shared\software\python\lib\site-packages (from chromadb) (1.39.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in d:\shared\software\python\lib\site-packages (from chromadb) (1.39.1)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in d:\shared\software\python\lib\site-packages (from chromadb) (1.39.1)
Requirement already satisfied: pypika>=0.48.9 in d:\shared\software\python\lib\site-packages (from chromadb) (0.48.9)
Requirement already satisfied: overrides>=7.3.1 in d:\shared\software\python\lib\site-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in d:\shared\software\python\lib\site-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in d:\shared\software\python\lib\site-packages (from chromadb) (1.76.0)
Requirement already satisfied: bcrypt>=4.0.1 in d:\shared\software\python\lib\site-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in d:\shared\software\python\lib\site-packages (from chromadb) (0.21.0)
Requirement already satisfied: kubernetes>=28.1.0 in d:\shared\software\python\lib\site-packages (from chromadb) (34.1.0)
Requirement already satisfied: mmh3>=4.0.1 in d:\shared\software\python\lib\site-packages (from chromadb) (5.2.0)
Requirement already satisfied: rich>=10.11.0 in d:\shared\software\python\lib\site-packages (from chromadb) (14.2.0)
Requirement already satisfied: jsonschema>=4.19.0 in d:\shared\software\python\lib\site-packages (from chromadb) (4.25.1)
Requirement already satisfied: six>=1.5 in c:\users\pirat\appdata\roaming\python\python313\site-packages (from posthog<6.0.0,>=2.4.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.2 in c:\users\pirat\appdata\roaming\python\python313\site-packages (from posthog<6.0.0,>=2.4.0->chromadb) (2.9.0.post0)
Requirement already satisfied: backoff>=1.10.0 in d:\shared\software\python\lib\site-packages (from posthog<6.0.0,>=2.4.0->chromadb) (2.2.1)
Requirement already satisfied: distro>=1.5.0 in d:\shared\software\python\lib\site-packages (from posthog<6.0.0,>=2.4.0->chromadb) (1.9.0)
Requirement already satisfied: pyproject_hooks in d:\shared\software\python\lib\site-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: colorama in c:\users\pirat\appdata\roaming\python\python313\site-packages (from build>=1.0.3->chromadb) (0.4.6)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in d:\shared\software\python\lib\site-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in d:\shared\software\python\lib\site-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in d:\shared\software\python\lib\site-packages (from jsonschema>=4.19.0->chromadb) (0.30.0)
Requirement already satisfied: google-auth>=1.0.1 in d:\shared\software\python\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.46.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in d:\shared\software\python\lib\site-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests-oauthlib in d:\shared\software\python\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: durationpy>=0.7 in d:\shared\software\python\lib\site-packages (from kubernetes>=28.1.0->chromadb) (0.10)
Requirement already satisfied: cachetools<7.0,>=2.0.0 in d:\shared\software\python\lib\site-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (6.2.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in d:\shared\software\python\lib\site-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in d:\shared\software\python\lib\site-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (4.9.1)
Requirement already satisfied: pyasn1>=0.1.3 in d:\shared\software\python\lib\site-packages (from rsa<5,>=3.1.4->google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.6.1)
Requirement already satisfied: coloredlogs in d:\shared\software\python\lib\site-packages (from onnxruntime>=1.14.1->chromadb) (15.0.1)
Requirement already satisfied: flatbuffers in d:\shared\software\python\lib\site-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf in d:\shared\software\python\lib\site-packages (from onnxruntime>=1.14.1->chromadb) (6.33.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in d:\shared\software\python\lib\site-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.1)
Requirement already satisfied: zipp>=3.20 in d:\shared\software\python\lib\site-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.23.0)
Requirement already satisfied: googleapis-common-protos~=1.57 in d:\shared\software\python\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.72.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.39.1 in d:\shared\software\python\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.39.1)
Requirement already satisfied: opentelemetry-proto==1.39.1 in d:\shared\software\python\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.39.1)
Requirement already satisfied: opentelemetry-semantic-conventions==0.60b1 in d:\shared\software\python\lib\site-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.60b1)
Requirement already satisfied: markdown-it-py>=2.2.0 in d:\shared\software\python\lib\site-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\pirat\appdata\roaming\python\python313\site-packages (from rich>=10.11.0->chromadb) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in d:\shared\software\python\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\shared\software\python\lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: click>=8.0.0 in d:\shared\software\python\lib\site-packages (from typer>=0.9.0->chromadb) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in d:\shared\software\python\lib\site-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: httptools>=0.6.3 in d:\shared\software\python\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.7.1)
Requirement already satisfied: watchfiles>=0.13 in d:\shared\software\python\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.1.1)
Requirement already satisfied: websockets>=10.4 in d:\shared\software\python\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: humanfriendly>=9.1 in d:\shared\software\python\lib\site-packages (from coloredlogs->onnxruntime>=1.14.1->chromadb) (10.0)
Requirement already satisfied: pyreadline3 in d:\shared\software\python\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime>=1.14.1->chromadb) (3.5.4)
Requirement already satisfied: MarkupSafe>=2.0 in d:\shared\software\python\lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: oauthlib>=3.0.0 in d:\shared\software\python\lib\site-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)
Installation complete. Restart the kernel now.

In [ ]:
from transformers import pipeline
from langchain_community.llms import HuggingFacePipeline
from langchain_community.vectorstores import Chroma

# ---------- Load Chroma ----------
vectordb = Chroma(
    collection_name="chatbot_finance",
    persist_directory="/kaggle/working/",
    embedding_function=None
)

retriever = vectordb.as_retriever(search_kwargs={"k": 2})


gen = pipeline(
    "text-generation",
    model="google/flan-t5-base",  
    max_new_tokens=80
)

llm = HuggingFacePipeline(pipeline=gen)

# ---------- Query ----------
query = "What is a savings account?"

docs = retriever.invoke(query)
context = " ".join(d.page_content[:200] for d in docs)

response = llm.invoke(f"Context: {context}\nQuestion: {query}\nAnswer:")

print(response)

config.json: 0.00B [00:00, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/990M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

Device set to use cpu
The model 'T5ForConditionalGeneration' is not supported for text-generation. Supported models are ['PeftModelForCausalLM', 'ApertusForCausalLM', 'ArceeForCausalLM', 'AriaTextForCausalLM', 'BambaForCausalLM', 'BartForCausalLM', 'BertLMHeadModel', 'BertGenerationDecoder', 'BigBirdForCausalLM', 'BigBirdPegasusForCausalLM', 'BioGptForCausalLM', 'BitNetForCausalLM', 'BlenderbotForCausalLM', 'BlenderbotSmallForCausalLM', 'BloomForCausalLM', 'BltForCausalLM', 'CamembertForCausalLM', 'LlamaForCausalLM', 'CodeGenForCausalLM', 'CohereForCausalLM', 'Cohere2ForCausalLM', 'CpmAntForCausalLM', 'CTRLLMHeadModel', 'Data2VecTextForCausalLM', 'DbrxForCausalLM', 'DeepseekV2ForCausalLM', 'DeepseekV3ForCausalLM', 'DiffLlamaForCausalLM', 'DogeForCausalLM', 'Dots1ForCausalLM', 'ElectraForCausalLM', 'Emu3ForCausalLM', 'ErnieForCausalLM', 'Ernie4_5ForCausalLM', 'Ernie4_5_MoeForCausalLM', 'Exaone4ForCausalLM', 'FalconForCausalLM', 'FalconH1ForCausalLM', 'FalconMambaForCausalLM', 'FlexOlmoForCausalLM', 'FuyuForCausalLM', 'GemmaForCausalLM', 'Gemma2ForCausalLM', 'Gemma3ForConditionalGeneration', 'Gemma3ForCausalLM', 'Gemma3nForConditionalGeneration', 'Gemma3nForCausalLM', 'GitForCausalLM', 'GlmForCausalLM', 'Glm4ForCausalLM', 'Glm4MoeForCausalLM', 'GotOcr2ForConditionalGeneration', 'GPT2LMHeadModel', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTNeoForCausalLM', 'GPTNeoXForCausalLM', 'GPTNeoXJapaneseForCausalLM', 'GptOssForCausalLM', 'GPTJForCausalLM', 'GraniteForCausalLM', 'GraniteMoeForCausalLM', 'GraniteMoeHybridForCausalLM', 'GraniteMoeSharedForCausalLM', 'HeliumForCausalLM', 'HunYuanDenseV1ForCausalLM', 'HunYuanMoEV1ForCausalLM', 'JambaForCausalLM', 'JetMoeForCausalLM', 'Lfm2ForCausalLM', 'LlamaForCausalLM', 'Llama4ForCausalLM', 'Llama4ForCausalLM', 'LongcatFlashForCausalLM', 'MambaForCausalLM', 'Mamba2ForCausalLM', 'MarianForCausalLM', 'MBartForCausalLM', 'MegaForCausalLM', 'MegatronBertForCausalLM', 'MiniMaxForCausalLM', 'MinistralForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'MllamaForCausalLM', 'ModernBertDecoderForCausalLM', 'MoshiForCausalLM', 'MptForCausalLM', 'MusicgenForCausalLM', 'MusicgenMelodyForCausalLM', 'MvpForCausalLM', 'NemotronForCausalLM', 'OlmoForCausalLM', 'Olmo2ForCausalLM', 'Olmo3ForCausalLM', 'OlmoeForCausalLM', 'OpenLlamaForCausalLM', 'OpenAIGPTLMHeadModel', 'OPTForCausalLM', 'PegasusForCausalLM', 'PersimmonForCausalLM', 'PhiForCausalLM', 'Phi3ForCausalLM', 'Phi4MultimodalForCausalLM', 'PhimoeForCausalLM', 'PLBartForCausalLM', 'ProphetNetForCausalLM', 'QDQBertLMHeadModel', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'Qwen3ForCausalLM', 'Qwen3MoeForCausalLM', 'Qwen3NextForCausalLM', 'RecurrentGemmaForCausalLM', 'ReformerModelWithLMHead', 'RemBertForCausalLM', 'RobertaForCausalLM', 'RobertaPreLayerNormForCausalLM', 'RoCBertForCausalLM', 'RoFormerForCausalLM', 'RwkvForCausalLM', 'SeedOssForCausalLM', 'SmolLM3ForCausalLM', 'Speech2Text2ForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM', 'TransfoXLLMHeadModel', 'TrOCRForCausalLM', 'VaultGemmaForCausalLM', 'WhisperForCausalLM', 'XGLMForCausalLM', 'XLMWithLMHeadModel', 'XLMProphetNetForCausalLM', 'XLMRobertaForCausalLM', 'XLMRobertaXLForCausalLM', 'XLNetLMHeadModel', 'xLSTMForCausalLM', 'XmodForCausalLM', 'ZambaForCausalLM', 'Zamba2ForCausalLM'].

Context: Is the Super Saver Account a normal Savings Account What is the frequency of interest payout for a Savings Account
Question: What is a savings account?
Answer:

In [6]:
pip install -U bitsandbytes

Requirement already satisfied: bitsandbytes in d:\shared\software\python\lib\site-packages (0.49.0)
Requirement already satisfied: torch<3,>=2.3 in d:\shared\software\python\lib\site-packages (from bitsandbytes) (2.9.1)
Requirement already satisfied: numpy>=1.17 in d:\shared\software\python\lib\site-packages (from bitsandbytes) (2.3.4)
Requirement already satisfied: packaging>=20.9 in c:\users\pirat\appdata\roaming\python\python313\site-packages (from bitsandbytes) (25.0)
Requirement already satisfied: filelock in d:\shared\software\python\lib\site-packages (from torch<3,>=2.3->bitsandbytes) (3.20.2)
Requirement already satisfied: typing-extensions>=4.10.0 in d:\shared\software\python\lib\site-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in d:\shared\software\python\lib\site-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in d:\shared\software\python\lib\site-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in d:\shared\software\python\lib\site-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in d:\shared\software\python\lib\site-packages (from torch<3,>=2.3->bitsandbytes) (2025.12.0)
Requirement already satisfied: setuptools in d:\shared\software\python\lib\site-packages (from torch<3,>=2.3->bitsandbytes) (80.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\shared\software\python\lib\site-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\shared\software\python\lib\site-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [7]:
pip install accelerate

Requirement already satisfied: accelerate in d:\shared\software\python\lib\site-packages (1.12.0)
Requirement already satisfied: numpy>=1.17 in d:\shared\software\python\lib\site-packages (from accelerate) (2.3.4)
Requirement already satisfied: packaging>=20.0 in c:\users\pirat\appdata\roaming\python\python313\site-packages (from accelerate) (25.0)
Requirement already satisfied: psutil in c:\users\pirat\appdata\roaming\python\python313\site-packages (from accelerate) (7.1.3)
Requirement already satisfied: pyyaml in d:\shared\software\python\lib\site-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in d:\shared\software\python\lib\site-packages (from accelerate) (2.9.1)
Requirement already satisfied: huggingface_hub>=0.21.0 in d:\shared\software\python\lib\site-packages (from accelerate) (0.36.0)
Requirement already satisfied: safetensors>=0.4.3 in d:\shared\software\python\lib\site-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock in d:\shared\software\python\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (3.20.2)
Requirement already satisfied: fsspec>=2023.5.0 in d:\shared\software\python\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (2025.12.0)
Requirement already satisfied: requests in d:\shared\software\python\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (2.32.5)
Requirement already satisfied: tqdm>=4.42.1 in d:\shared\software\python\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\shared\software\python\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in d:\shared\software\python\lib\site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in d:\shared\software\python\lib\site-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in d:\shared\software\python\lib\site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: setuptools in d:\shared\software\python\lib\site-packages (from torch>=2.0.0->accelerate) (80.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\shared\software\python\lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: colorama in c:\users\pirat\appdata\roaming\python\python313\site-packages (from tqdm>=4.42.1->huggingface_hub>=0.21.0->accelerate) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in d:\shared\software\python\lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\shared\software\python\lib\site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\shared\software\python\lib\site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\shared\software\python\lib\site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\shared\software\python\lib\site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (2025.11.12)
Note: you may need to restart the kernel to use updated packages.

In [8]:
import torch
print(torch.version.cuda)

None

In [11]:
!pip list | grep bitsandbytes
!pip list | grep accelerate

'grep' is not recognized as an internal or external command,
operable program or batch file.
'grep' is not recognized as an internal or external command,
operable program or batch file.

In [14]:
!pip uninstall bitsandbytes accelerate -y
!pip install bitsandbytes accelerate

WARNING: Skipping bitsandbytes as it is not installed.
WARNING: Skipping accelerate as it is not installed.

Defaulting to user installation because normal site-packages is not writeable
Collecting bitsandbytes
  Downloading bitsandbytes-0.48.2-py3-none-win_amd64.whl (59.0 MB)
Collecting accelerate
  Downloading accelerate-1.10.1-py3-none-any.whl (374 kB)
Collecting torch<3,>=2.3
  Downloading torch-2.8.0-cp39-cp39-win_amd64.whl (241.2 MB)
Requirement already satisfied: numpy>=1.17 in c:\users\pirat\appdata\roaming\python\python39\site-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in c:\users\pirat\appdata\roaming\python\python39\site-packages (from bitsandbytes) (25.0)
Requirement already satisfied: pyyaml in c:\users\pirat\appdata\roaming\python\python39\site-packages (from accelerate) (6.0.3)
Collecting psutil
  Downloading psutil-7.2.1-cp37-abi3-win_amd64.whl (136 kB)
Collecting safetensors>=0.4.3
  Downloading safetensors-0.7.0-cp38-abi3-win_amd64.whl (341 kB)
Collecting huggingface_hub>=0.21.0
  Downloading huggingface_hub-1.2.4-py3-none-any.whl (520 kB)
Collecting fsspec>=2023.5.0
  Downloading fsspec-2025.10.0-py3-none-any.whl (200 kB)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\pirat\appdata\roaming\python\python39\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.64.0)
Collecting typer-slim
  Downloading typer_slim-0.21.1-py3-none-any.whl (47 kB)
Collecting hf-xet<2.0.0,>=1.2.0
  Downloading hf_xet-1.2.0-cp37-abi3-win_amd64.whl (2.9 MB)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\pirat\appdata\roaming\python\python39\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Collecting shellingham
  Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Requirement already satisfied: filelock in c:\users\pirat\appdata\roaming\python\python39\site-packages (from huggingface_hub>=0.21.0->accelerate) (3.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\pirat\appdata\roaming\python\python39\site-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: idna in c:\users\pirat\appdata\roaming\python\python39\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.3)
Requirement already satisfied: anyio in c:\users\pirat\appdata\roaming\python\python39\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.12.0)
Requirement already satisfied: certifi in c:\users\pirat\appdata\roaming\python\python39\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2022.6.15)
Requirement already satisfied: httpcore==1.* in c:\users\pirat\appdata\roaming\python\python39\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\pirat\appdata\roaming\python\python39\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Collecting networkx
  Downloading networkx-3.2.1-py3-none-any.whl (1.6 MB)
Requirement already satisfied: jinja2 in c:\users\pirat\appdata\roaming\python\python39\site-packages (from torch<3,>=2.3->bitsandbytes) (3.0.3)
Collecting sympy>=1.13.3
  Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
Collecting mpmath<1.4,>=1.1.0
  Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
Requirement already satisfied: colorama in c:\users\pirat\appdata\roaming\python\python39\site-packages (from tqdm>=4.42.1->huggingface_hub>=0.21.0->accelerate) (0.4.4)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\pirat\appdata\roaming\python\python39\site-packages (from anyio->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\pirat\appdata\roaming\python\python39\site-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (2.0.1)
Requirement already satisfied: click>=8.0.0 in c:\users\pirat\appdata\roaming\python\python39\site-packages (from typer-slim->huggingface_hub>=0.21.0->accelerate) (8.0.3)
Installing collected packages: mpmath, typer-slim, sympy, shellingham, networkx, hf-xet, fsspec, torch, safetensors, psutil, huggingface-hub, bitsandbytes, accelerate
Successfully installed accelerate-1.10.1 bitsandbytes-0.48.2 fsspec-2025.10.0 hf-xet-1.2.0 huggingface-hub-1.2.4 mpmath-1.3.0 networkx-3.2.1 psutil-7.2.1 safetensors-0.7.0 shellingham-1.5.4 sympy-1.14.0 torch-2.8.0 typer-slim-0.21.1

  WARNING: The script isympy.exe is installed in 'C:\Users\pirat\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts torchfrtrace.exe and torchrun.exe are installed in 'C:\Users\pirat\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts hf.exe and tiny-agents.exe are installed in 'C:\Users\pirat\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts accelerate-config.exe, accelerate-estimate-memory.exe, accelerate-launch.exe, accelerate-merge-weights.exe and accelerate.exe are installed in 'C:\Users\pirat\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: You are using pip version 21.2.4; however, version 25.3 is available.
You should consider upgrading via the 'C:\Program Files\Python39\python.exe -m pip install --upgrade pip' command.

In [17]:
import transformers
from transformers import AutoTokenizer

model_id = "google/flan-t5-base"

model = transformers.AutoModelForSeq2SeqLM.from_pretrained(model_id)
tokenizer = AutoTokenizer.from_pretrained(model_id)

print("Model and tokenizer loaded (CPU/GPU safe)")

Model and tokenizer loaded (CPU/GPU safe)

### Building Hugging Face Pipeline to Build LLM Function

In [18]:
# Initialize the query pipeline with increased max_length
query_pipeline = transformers.pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    torch_dtype=torch.float16,
    max_length=6000,  # Increase max_length
    max_new_tokens=500,  # Control the number of new tokens generated
    device_map="auto",
)

`torch_dtype` is deprecated! Use `dtype` instead!
Device set to use cpu
The model 'T5ForConditionalGeneration' is not supported for text-generation. Supported models are ['PeftModelForCausalLM', 'ApertusForCausalLM', 'ArceeForCausalLM', 'AriaTextForCausalLM', 'BambaForCausalLM', 'BartForCausalLM', 'BertLMHeadModel', 'BertGenerationDecoder', 'BigBirdForCausalLM', 'BigBirdPegasusForCausalLM', 'BioGptForCausalLM', 'BitNetForCausalLM', 'BlenderbotForCausalLM', 'BlenderbotSmallForCausalLM', 'BloomForCausalLM', 'BltForCausalLM', 'CamembertForCausalLM', 'LlamaForCausalLM', 'CodeGenForCausalLM', 'CohereForCausalLM', 'Cohere2ForCausalLM', 'CpmAntForCausalLM', 'CTRLLMHeadModel', 'Data2VecTextForCausalLM', 'DbrxForCausalLM', 'DeepseekV2ForCausalLM', 'DeepseekV3ForCausalLM', 'DiffLlamaForCausalLM', 'DogeForCausalLM', 'Dots1ForCausalLM', 'ElectraForCausalLM', 'Emu3ForCausalLM', 'ErnieForCausalLM', 'Ernie4_5ForCausalLM', 'Ernie4_5_MoeForCausalLM', 'Exaone4ForCausalLM', 'FalconForCausalLM', 'FalconH1ForCausalLM', 'FalconMambaForCausalLM', 'FlexOlmoForCausalLM', 'FuyuForCausalLM', 'GemmaForCausalLM', 'Gemma2ForCausalLM', 'Gemma3ForConditionalGeneration', 'Gemma3ForCausalLM', 'Gemma3nForConditionalGeneration', 'Gemma3nForCausalLM', 'GitForCausalLM', 'GlmForCausalLM', 'Glm4ForCausalLM', 'Glm4MoeForCausalLM', 'GotOcr2ForConditionalGeneration', 'GPT2LMHeadModel', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTNeoForCausalLM', 'GPTNeoXForCausalLM', 'GPTNeoXJapaneseForCausalLM', 'GptOssForCausalLM', 'GPTJForCausalLM', 'GraniteForCausalLM', 'GraniteMoeForCausalLM', 'GraniteMoeHybridForCausalLM', 'GraniteMoeSharedForCausalLM', 'HeliumForCausalLM', 'HunYuanDenseV1ForCausalLM', 'HunYuanMoEV1ForCausalLM', 'JambaForCausalLM', 'JetMoeForCausalLM', 'Lfm2ForCausalLM', 'LlamaForCausalLM', 'Llama4ForCausalLM', 'Llama4ForCausalLM', 'LongcatFlashForCausalLM', 'MambaForCausalLM', 'Mamba2ForCausalLM', 'MarianForCausalLM', 'MBartForCausalLM', 'MegaForCausalLM', 'MegatronBertForCausalLM', 'MiniMaxForCausalLM', 'MinistralForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'MllamaForCausalLM', 'ModernBertDecoderForCausalLM', 'MoshiForCausalLM', 'MptForCausalLM', 'MusicgenForCausalLM', 'MusicgenMelodyForCausalLM', 'MvpForCausalLM', 'NemotronForCausalLM', 'OlmoForCausalLM', 'Olmo2ForCausalLM', 'Olmo3ForCausalLM', 'OlmoeForCausalLM', 'OpenLlamaForCausalLM', 'OpenAIGPTLMHeadModel', 'OPTForCausalLM', 'PegasusForCausalLM', 'PersimmonForCausalLM', 'PhiForCausalLM', 'Phi3ForCausalLM', 'Phi4MultimodalForCausalLM', 'PhimoeForCausalLM', 'PLBartForCausalLM', 'ProphetNetForCausalLM', 'QDQBertLMHeadModel', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'Qwen3ForCausalLM', 'Qwen3MoeForCausalLM', 'Qwen3NextForCausalLM', 'RecurrentGemmaForCausalLM', 'ReformerModelWithLMHead', 'RemBertForCausalLM', 'RobertaForCausalLM', 'RobertaPreLayerNormForCausalLM', 'RoCBertForCausalLM', 'RoFormerForCausalLM', 'RwkvForCausalLM', 'SeedOssForCausalLM', 'SmolLM3ForCausalLM', 'Speech2Text2ForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM', 'TransfoXLLMHeadModel', 'TrOCRForCausalLM', 'VaultGemmaForCausalLM', 'WhisperForCausalLM', 'XGLMForCausalLM', 'XLMWithLMHeadModel', 'XLMProphetNetForCausalLM', 'XLMRobertaForCausalLM', 'XLMRobertaXLForCausalLM', 'XLNetLMHeadModel', 'xLSTMForCausalLM', 'XmodForCausalLM', 'ZambaForCausalLM', 'Zamba2ForCausalLM'].

### Testing the LLM

In [20]:
from IPython.display import display, Markdown
from langchain_community.llms import HuggingFacePipeline

def colorize_text(text):
    for word, color in zip(
        ["Reasoning", "Question", "Answer", "Total time"],
        ["blue", "red", "green", "magenta"]
    ):
        text = text.replace(
            f"{word}:", f"\n\n**<font color='{color}'>{word}:</font>**"
        )
    return text

# Create LLM wrapper
llm = HuggingFacePipeline(pipeline=query_pipeline)

question = "What is Chatbot and How it used in Finance Domain?"

# ✅ CORRECT invocation
response = llm.invoke(question)

full_response = f"Question: {question}\nAnswer: {response}"

display(Markdown(colorize_text(full_response)))

**<font color='red'>Question:</font>** What is Chatbot and How it used in Finance Domain?


**<font color='green'>Answer:</font>** What is Chatbot and How it used in Finance Domain?

### Building the RAG QA Chain using Langchain and Create Chatbot Interface

In [24]:
import os
import warnings
warnings.filterwarnings("ignore")

from langchain_community.llms import HuggingFaceHub
from langchain_community.vectorstores import Chroma

# ------------------ Hugging Face Token ------------------
os.environ["HUGGINGFACEHUB_API_TOKEN"] = "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"

# ------------------ Load Vector Store (DEFINE langchain_chroma) ------------------
langchain_chroma = Chroma(
    collection_name="chatbot_finance",
    persist_directory="/kaggle/working/",
    embedding_function=None
)

retriever = langchain_chroma.as_retriever(search_kwargs={"k": 1})

# ------------------ Load LLM (task is REQUIRED) ------------------
llm = HuggingFaceHub(
    repo_id="google/flan-t5-base",
    task="text2text-generation",
    model_kwargs={
        "temperature": 0.2,
        "max_new_tokens": 256
    }
)

# ------------------ Prompt Builder ------------------
def build_prompt(context, question):
    return f"""
You are a Finance Q&A Expert.
Answer the question using ONLY the context below.
If you don't know the answer, say "Sorry, I don't know."

Context:
{context}

Question:
{question}

Answer:
"""

# ------------------ Chat Function ------------------
def chat_with_rag():
    print("Welcome to the GenAI Financial Chatbot. Type 'exit' to quit.\n")

    while True:
        query = input("You: ")
        if query.lower() in ["exit", "quit"]:
            print("Chatbot: Goodbye!")
            break

        try:
            docs = retriever.invoke(query)
            context = " ".join(d.page_content for d in docs)

            prompt = build_prompt(context, query)
            response = llm.invoke(prompt)

            print(f"\nChatbot: {response}\n")

        except Exception as e:
            print(f"Error: {e}")

# ------------------ Run Chat ------------------
chat_with_rag()

Welcome to the GenAI Financial Chatbot. Type 'exit' to quit.

Error: 'InferenceClient' object has no attribute 'post'
Chatbot: Goodbye!